"""关键词替换工具：在扫描/解析阶段应用用户在设置页配置的规则"""
from typing import List, Optional

from backend.models import KeywordReplaceRule
from sqlalchemy.orm import Session


def load_rules(db: Session, scope: str) -> List[KeywordReplaceRule]:
    """加载某作用域下已启用的规则，按 sort_order、id 升序。"""
    return db.query(KeywordReplaceRule).filter(
        KeywordReplaceRule.scope == scope,
        KeywordReplaceRule.enabled == True,
    ).order_by(KeywordReplaceRule.sort_order, KeywordReplaceRule.id).all()


def apply_rules(text: Optional[str], rules: List[KeywordReplaceRule]) -> Optional[str]:
    """按顺序对文本应用规则；空文本或空规则原样返回。"""
    if not text or not rules:
        return text
    for r in rules:
        p = (r.pattern or '')
        if p:
            text = text.replace(p, r.replacement or '')
    return text


# 预置关键词替换规则（去文件名水印），随启动补齐进数据库，用户可见、可增删改查。
# 与 Android 端 DEFAULT_KEYWORD_RULES 保持同步：作用域均为 scan（扫描阶段作用于文件名），
# replacement 为空串表示删除。若用户不想要某条，建议在界面"禁用"而非"删除"，否则下次启动会被重新补齐。
DEFAULT_KEYWORD_RULES = [
    {'scope': 'scan', 'pattern': '[草2莓]', 'replacement': '', 'sort_order': 1},
    {'scope': 'scan', 'pattern': '【草2莓', 'replacement': '', 'sort_order': 2},
    {'scope': 'scan', 'pattern': '【草2莓】', 'replacement': '', 'sort_order': 3},
    {'scope': 'scan', 'pattern': '[草 莓]', 'replacement': '', 'sort_order': 4},
    {'scope': 'scan', 'pattern': '[草 莓', 'replacement': '', 'sort_order': 5},
    {'scope': 'scan', 'pattern': '【lili】', 'replacement': '', 'sort_order': 6},
    {'scope': 'scan', 'pattern': '（l.i.）', 'replacement': '', 'sort_order': 7},
    {'scope': 'scan', 'pattern': '(l.i.）', 'replacement': '', 'sort_order': 8},
    {'scope': 'scan', 'pattern': '（l.i.)', 'replacement': '', 'sort_order': 9},
    {'scope': 'scan', 'pattern': '(l.i.)', 'replacement': '', 'sort_order': 10},
    # —— 以下为 caomei / 3167 937770 水印系列及扩展名修正（与 APP/鸿蒙端同步）——
    # 顺序约定：① 含「の企鹅3167 937770」的完整变体须先于裸「の企鹅3167 937770」，
    # 否则裸规则先吃掉尾部、残留孤立前缀；② 成对括号变体须先于只去开头括号的变体，
    # 否则残留孤立括号。
    {'scope': 'scan', 'pattern': '..txt', 'replacement': '.txt', 'sort_order': 11},
    {'scope': 'scan', 'pattern': '【草莓】', 'replacement': '', 'sort_order': 12},
    {'scope': 'scan', 'pattern': '【草 莓', 'replacement': '', 'sort_order': 13},
    {'scope': 'scan', 'pattern': '【＋V信kxee6699】', 'replacement': '', 'sort_order': 14},
    {'scope': 'scan', 'pattern': '.3167 937770', 'replacement': '', 'sort_order': 15},
    {'scope': 'scan', 'pattern': '【颜3167 937770', 'replacement': '', 'sort_order': 16},
    {'scope': 'scan', 'pattern': '【Q主caomeiの企鹅3167 937770】', 'replacement': '', 'sort_order': 17},
    {'scope': 'scan', 'pattern': '【Q主caomei】', 'replacement': '', 'sort_order': 18},
    {'scope': 'scan', 'pattern': '_caomeiの企鹅3167 937770_', 'replacement': '', 'sort_order': 19},
    {'scope': 'scan', 'pattern': '（caomeiの企鹅3167 937770', 'replacement': '', 'sort_order': 20},
    {'scope': 'scan', 'pattern': '(caomeiの企鹅3167 937770', 'replacement': '', 'sort_order': 21},
    {'scope': 'scan', 'pattern': '【qzcaomeiの企鹅3167 937770', 'replacement': '', 'sort_order': 22},
    {'scope': 'scan', 'pattern': '.QZcaomeiの企鹅3167 937770', 'replacement': '', 'sort_order': 23},
    {'scope': 'scan', 'pattern': '_caomeiの企鹅3167 937770', 'replacement': '', 'sort_order': 24},
    {'scope': 'scan', 'pattern': '.caomeiの企鹅3167 937770', 'replacement': '', 'sort_order': 25},
    {'scope': 'scan', 'pattern': 'の企鹅3167 937770', 'replacement': '', 'sort_order': 26},
    {'scope': 'scan', 'pattern': '[3167 937770]', 'replacement': '', 'sort_order': 27},
    {'scope': 'scan', 'pattern': '[3167 937770', 'replacement': '', 'sort_order': 28},
    {'scope': 'scan', 'pattern': '3167937770', 'replacement': '', 'sort_order': 29},
    {'scope': 'scan', 'pattern': '_3167 937770', 'replacement': '', 'sort_order': 30},
    {'scope': 'scan', 'pattern': '（颜3167 937770', 'replacement': '', 'sort_order': 31},
    {'scope': 'scan', 'pattern': '【3167 937770]', 'replacement': '', 'sort_order': 32},
    {'scope': 'scan', 'pattern': '_.txt', 'replacement': '.txt', 'sort_order': 33},
    # —— 与 Android 端同步的默认替换规则 ——
    {'scope': 'scan', 'pattern': '【YLW】', 'replacement': '', 'sort_order': 34},
    {'scope': 'scan', 'pattern': '『推』', 'replacement': '', 'sort_order': 35},
    {'scope': 'scan', 'pattern': '【昭昭明月BG】', 'replacement': '', 'sort_order': 36},
    {'scope': 'scan', 'pattern': '【昭昭明月BL】', 'replacement': '', 'sort_order': 37},
    {'scope': 'scan', 'pattern': '【推荐】', 'replacement': '', 'sort_order': 38},
    {'scope': 'scan', 'pattern': '【全本校对】', 'replacement': '', 'sort_order': 39},
    {'scope': 'scan', 'pattern': '【全本精校】', 'replacement': '', 'sort_order': 40},
    {'scope': 'scan', 'pattern': '【BL】', 'replacement': '', 'sort_order': 41},
    {'scope': 'scan', 'pattern': '【BG】', 'replacement': '', 'sort_order': 42},
    {'scope': 'scan', 'pattern': '【YLW连载】', 'replacement': '', 'sort_order': 43},
    {'scope': 'scan', 'pattern': '【棠】', 'replacement': '', 'sort_order': 44},
    {'scope': 'scan', 'pattern': '【公众号：推文日记】', 'replacement': '', 'sort_order': 45},
    {'scope': 'scan', 'pattern': '（1-1强制）', 'replacement': '', 'sort_order': 47},
    {'scope': 'scan', 'pattern': '(1v1)', 'replacement': '', 'sort_order': 48},
    {'scope': 'scan', 'pattern': '（1v1）', 'replacement': '', 'sort_order': 49},
    {'scope': 'scan', 'pattern': '（1v1, 高H）', 'replacement': '', 'sort_order': 50},
    {'scope': 'scan', 'pattern': '（1v1, 直掰弯）', 'replacement': '', 'sort_order': 51},
    {'scope': 'scan', 'pattern': '（1v2）', 'replacement': '', 'sort_order': 52},
    {'scope': 'scan', 'pattern': '（1vN）', 'replacement': '', 'sort_order': 53},
    {'scope': 'scan', 'pattern': '（1vn）', 'replacement': '', 'sort_order': 54},
    {'scope': 'scan', 'pattern': '（2025年重修版）', 'replacement': '', 'sort_order': 55},
    {'scope': 'scan', 'pattern': '（3P_强制）', 'replacement': '', 'sort_order': 56},
    {'scope': 'scan', 'pattern': '(ABO)', 'replacement': '', 'sort_order': 57},
    {'scope': 'scan', 'pattern': '（ABO）', 'replacement': '', 'sort_order': 58},
    {'scope': 'scan', 'pattern': '（ABO, 1v1）', 'replacement': '', 'sort_order': 59},
    {'scope': 'scan', 'pattern': '（ABO, NP）', 'replacement': '', 'sort_order': 60},
    {'scope': 'scan', 'pattern': '（ABO, 穿越, 生子）', 'replacement': '', 'sort_order': 61},
    {'scope': 'scan', 'pattern': '（ABO, 高H）', 'replacement': '', 'sort_order': 62},
    {'scope': 'scan', 'pattern': '（ABO, 骨科）', 'replacement': '', 'sort_order': 63},
    {'scope': 'scan', 'pattern': '（ABO, 破镜重圆）', 'replacement': '', 'sort_order': 64},
    {'scope': 'scan', 'pattern': '（ABO, 破镜重圆, 骨科）', 'replacement': '', 'sort_order': 65},
    {'scope': 'scan', 'pattern': '（ABO, 破镜重圆, 生子）', 'replacement': '', 'sort_order': 66},
    {'scope': 'scan', 'pattern': '（ABO, 强制爱, NP, 高H）', 'replacement': '', 'sort_order': 67},
    {'scope': 'scan', 'pattern': '（ABO, 强制爱, 骨科, NP）', 'replacement': '', 'sort_order': 68},
    {'scope': 'scan', 'pattern': '（ABO, 强制爱, 美强）', 'replacement': '', 'sort_order': 69},
    {'scope': 'scan', 'pattern': '（ABO, 强制爱, 异能）', 'replacement': '', 'sort_order': 70},
    {'scope': 'scan', 'pattern': '（ABO, 弱强, 受宠攻）', 'replacement': '', 'sort_order': 71},
    {'scope': 'scan', 'pattern': '（ABO, 生子）', 'replacement': '', 'sort_order': 72},
    {'scope': 'scan', 'pattern': '（ABO, 生子, 高H）', 'replacement': '', 'sort_order': 73},
    {'scope': 'scan', 'pattern': '（ABO, 双性, NP）', 'replacement': '', 'sort_order': 74},
    {'scope': 'scan', 'pattern': '（ABO, 双性, 高H）', 'replacement': '', 'sort_order': 75},
    {'scope': 'scan', 'pattern': '（ABO, 双性, 生子, 产乳）', 'replacement': '', 'sort_order': 76},
    {'scope': 'scan', 'pattern': '（ABO, 天作之合, 1v1）', 'replacement': '', 'sort_order': 77},
    {'scope': 'scan', 'pattern': '（ABO, 西方, 强制爱, NP）', 'replacement': '', 'sort_order': 78},
    {'scope': 'scan', 'pattern': '（ABO, 先婚后爱）', 'replacement': '', 'sort_order': 79},
    {'scope': 'scan', 'pattern': '（ABO, 先婚后爱, 高H）', 'replacement': '', 'sort_order': 80},
    {'scope': 'scan', 'pattern': '（ABO, 先婚后爱, 互攻）', 'replacement': '', 'sort_order': 81},
    {'scope': 'scan', 'pattern': '（ABO, 先婚后爱, 强制爱）', 'replacement': '', 'sort_order': 82},
    {'scope': 'scan', 'pattern': '（ABO, 相爱相杀, 生子, 高H）', 'replacement': '', 'sort_order': 83},
    {'scope': 'scan', 'pattern': '（ABO, 阴差阳错, NTR, NP）', 'replacement': '', 'sort_order': 84},
    {'scope': 'scan', 'pattern': '（ABO, 娱乐圈, 暗恋, 重生）', 'replacement': '', 'sort_order': 85},
    {'scope': 'scan', 'pattern': '（ABO, 娱乐圈, 强制爱）', 'replacement': '', 'sort_order': 86},
    {'scope': 'scan', 'pattern': '（ABO强制爱_all橘）', 'replacement': '', 'sort_order': 87},
    {'scope': 'scan', 'pattern': '(BDSM)', 'replacement': '', 'sort_order': 88},
    {'scope': 'scan', 'pattern': '（BDSM）', 'replacement': '', 'sort_order': 89},
    {'scope': 'scan', 'pattern': '（BE, 美强）', 'replacement': '', 'sort_order': 90},
    {'scope': 'scan', 'pattern': '（BE, 强制爱, NP）', 'replacement': '', 'sort_order': 91},
    {'scope': 'scan', 'pattern': '（BE, 校园）', 'replacement': '', 'sort_order': 92},
    {'scope': 'scan', 'pattern': '(Ending)', 'replacement': '', 'sort_order': 93},
    {'scope': 'scan', 'pattern': '（futa np）', 'replacement': '', 'sort_order': 94},
    {'scope': 'scan', 'pattern': '（H_C, 暗黑, MB）', 'replacement': '', 'sort_order': 95},
    {'scope': 'scan', 'pattern': '（H_C, 暗恋）', 'replacement': '', 'sort_order': 96},
    {'scope': 'scan', 'pattern': '（H_C, 黑色幽默, 美强）', 'replacement': '', 'sort_order': 97},
    {'scope': 'scan', 'pattern': '（H_C, 美强, NP）', 'replacement': '', 'sort_order': 98},
    {'scope': 'scan', 'pattern': '（H_C, 日系, 破镜重圆）', 'replacement': '', 'sort_order': 99},
    {'scope': 'scan', 'pattern': '（H_C, 哨兵向导, 1v1）', 'replacement': '', 'sort_order': 100},
    {'scope': 'scan', 'pattern': '（H_C, 双性, 破镜重圆）', 'replacement': '', 'sort_order': 101},
    {'scope': 'scan', 'pattern': '（H_C, 西方, 强制爱, 高H）', 'replacement': '', 'sort_order': 102},
    {'scope': 'scan', 'pattern': '(Happy)', 'replacement': '', 'sort_order': 103},
    {'scope': 'scan', 'pattern': '（MB）', 'replacement': '', 'sort_order': 104},
    {'scope': 'scan', 'pattern': '（n）', 'replacement': '', 'sort_order': 105},
    {'scope': 'scan', 'pattern': '(NP)', 'replacement': '', 'sort_order': 106},
    {'scope': 'scan', 'pattern': '（NP）', 'replacement': '', 'sort_order': 107},
    {'scope': 'scan', 'pattern': '（NP, BDSM）', 'replacement': '', 'sort_order': 108},
    {'scope': 'scan', 'pattern': '（NP, 高H）', 'replacement': '', 'sort_order': 109},
    {'scope': 'scan', 'pattern': '（NP, 直掰弯）', 'replacement': '', 'sort_order': 110},
    {'scope': 'scan', 'pattern': '(NTR)', 'replacement': '', 'sort_order': 111},
    {'scope': 'scan', 'pattern': '（NTR）', 'replacement': '', 'sort_order': 112},
    {'scope': 'scan', 'pattern': '（NTR, 父子）', 'replacement': '', 'sort_order': 113},
    {'scope': 'scan', 'pattern': '（NTR, 论坛体, 高H）', 'replacement': '', 'sort_order': 114},
    {'scope': 'scan', 'pattern': '（NTR, 强制爱）', 'replacement': '', 'sort_order': 115},
    {'scope': 'scan', 'pattern': '（OE）', 'replacement': '', 'sort_order': 116},
    {'scope': 'scan', 'pattern': '（OE, 骨科, NP, 高H）', 'replacement': '', 'sort_order': 117},
    {'scope': 'scan', 'pattern': '（OE, 惊悚, 美强）', 'replacement': '', 'sort_order': 118},
    {'scope': 'scan', 'pattern': '（OE, 开放关系）', 'replacement': '', 'sort_order': 119},
    {'scope': 'scan', 'pattern': '（OE, 星际, ABO）', 'replacement': '', 'sort_order': 120},
    {'scope': 'scan', 'pattern': '(Open)', 'replacement': '', 'sort_order': 121},
    {'scope': 'scan', 'pattern': '（PTSD, 强制爱）', 'replacement': '', 'sort_order': 122},
    {'scope': 'scan', 'pattern': '(SP _ BDSM)', 'replacement': '', 'sort_order': 123},
    {'scope': 'scan', 'pattern': '（sp）', 'replacement': '', 'sort_order': 124},
    {'scope': 'scan', 'pattern': '（SP训诫）', 'replacement': '', 'sort_order': 125},
    {'scope': 'scan', 'pattern': '(暧昧)', 'replacement': '', 'sort_order': 126},
    {'scope': 'scan', 'pattern': '(暗黑)', 'replacement': '', 'sort_order': 127},
    {'scope': 'scan', 'pattern': '（暗黑, ABO, 骨科）', 'replacement': '', 'sort_order': 128},
    {'scope': 'scan', 'pattern': '（暗黑, 骨科, 下克上, BDSM）', 'replacement': '', 'sort_order': 129},
    {'scope': 'scan', 'pattern': '（暗黑, 强制爱, 1v1, 触手）', 'replacement': '', 'sort_order': 130},
    {'scope': 'scan', 'pattern': '（暗黑, 强制爱, BDSM）', 'replacement': '', 'sort_order': 131},
    {'scope': 'scan', 'pattern': '（暗黑, 强制爱, NP）', 'replacement': '', 'sort_order': 132},
    {'scope': 'scan', 'pattern': '（暗黑, 双性）', 'replacement': '', 'sort_order': 133},
    {'scope': 'scan', 'pattern': '（暗黑, 双性, 前世今生, 无限流）', 'replacement': '', 'sort_order': 134},
    {'scope': 'scan', 'pattern': '（暗黑, 重口, 高H）', 'replacement': '', 'sort_order': 135},
    {'scope': 'scan', 'pattern': '(暗恋)', 'replacement': '', 'sort_order': 136},
    {'scope': 'scan', 'pattern': '（暗恋）', 'replacement': '', 'sort_order': 137},
    {'scope': 'scan', 'pattern': '（暗恋, 1v1）', 'replacement': '', 'sort_order': 138},
    {'scope': 'scan', 'pattern': '（暗恋, NP）', 'replacement': '', 'sort_order': 139},
    {'scope': 'scan', 'pattern': '（暗恋, 天作之合, 互攻）', 'replacement': '', 'sort_order': 140},
    {'scope': 'scan', 'pattern': '（暗恋, 异能）', 'replacement': '', 'sort_order': 141},
    {'scope': 'scan', 'pattern': '（暗恋, 忠犬）', 'replacement': '', 'sort_order': 142},
    {'scope': 'scan', 'pattern': '（暗恋, 重生）', 'replacement': '', 'sort_order': 143},
    {'scope': 'scan', 'pattern': '（悲剧, BE）', 'replacement': '', 'sort_order': 144},
    {'scope': 'scan', 'pattern': '（悲剧, BE, 现实主义）', 'replacement': '', 'sort_order': 145},
    {'scope': 'scan', 'pattern': '（被螃蟹扛著的鱼）', 'replacement': '', 'sort_order': 146},
    {'scope': 'scan', 'pattern': '(产乳)', 'replacement': '', 'sort_order': 147},
    {'scope': 'scan', 'pattern': '(虫族)', 'replacement': '', 'sort_order': 148},
    {'scope': 'scan', 'pattern': '（虫族, 双性, 生子, 产乳, 高H）', 'replacement': '', 'sort_order': 149},
    {'scope': 'scan', 'pattern': '（穿越, NP）', 'replacement': '', 'sort_order': 150},
    {'scope': 'scan', 'pattern': '（穿越, 系统, 美强, 1v1）', 'replacement': '', 'sort_order': 151},
    {'scope': 'scan', 'pattern': '(大纲)', 'replacement': '', 'sort_order': 152},
    {'scope': 'scan', 'pattern': '（大纲, 强制爱, NP）', 'replacement': '', 'sort_order': 153},
    {'scope': 'scan', 'pattern': '(大古代)', 'replacement': '', 'sort_order': 154},
    {'scope': 'scan', 'pattern': '(大未来)', 'replacement': '', 'sort_order': 155},
    {'scope': 'scan', 'pattern': '(大现代)', 'replacement': '', 'sort_order': 156},
    {'scope': 'scan', 'pattern': '(大长篇)', 'replacement': '', 'sort_order': 157},
    {'scope': 'scan', 'pattern': '(大主受视角)', 'replacement': '', 'sort_order': 158},
    {'scope': 'scan', 'pattern': '（第二部）', 'replacement': '', 'sort_order': 159},
    {'scope': 'scan', 'pattern': '（暂时缓更版)', 'replacement': '', 'sort_order': 160},
    {'scope': 'scan', 'pattern': '(第三人称)', 'replacement': '', 'sort_order': 161},
    {'scope': 'scan', 'pattern': '(第一人称)', 'replacement': '', 'sort_order': 162},
    {'scope': 'scan', 'pattern': '(第一人称）', 'replacement': '', 'sort_order': 163},
    {'scope': 'scan', 'pattern': '（东南亚, 天作之合）', 'replacement': '', 'sort_order': 164},
    {'scope': 'scan', 'pattern': '（动物世界, 双性, NP, 人兽, 高H）', 'replacement': '', 'sort_order': 165},
    {'scope': 'scan', 'pattern': '(短篇)', 'replacement': '', 'sort_order': 166},
    {'scope': 'scan', 'pattern': '(多CP高H双男主)', 'replacement': '', 'sort_order': 167},
    {'scope': 'scan', 'pattern': '（多重视角, 1v1）', 'replacement': '', 'sort_order': 168},
    {'scope': 'scan', 'pattern': '（父子）', 'replacement': '', 'sort_order': 169},
    {'scope': 'scan', 'pattern': '（父子, 1v1）', 'replacement': '', 'sort_order': 170},
    {'scope': 'scan', 'pattern': '（父子, 高H）', 'replacement': '', 'sort_order': 171},
    {'scope': 'scan', 'pattern': '(高H)', 'replacement': '', 'sort_order': 172},
    {'scope': 'scan', 'pattern': '（各种炖肉）', 'replacement': '', 'sort_order': 173},
    {'scope': 'scan', 'pattern': '（公路文）', 'replacement': '', 'sort_order': 174},
    {'scope': 'scan', 'pattern': '(攻宠受)', 'replacement': '', 'sort_order': 175},
    {'scope': 'scan', 'pattern': '(宫廷侯爵)', 'replacement': '', 'sort_order': 176},
    {'scope': 'scan', 'pattern': '(狗血)', 'replacement': '', 'sort_order': 177},
    {'scope': 'scan', 'pattern': '(古代)', 'replacement': '', 'sort_order': 178},
    {'scope': 'scan', 'pattern': '(骨科)', 'replacement': '', 'sort_order': 179},
    {'scope': 'scan', 'pattern': '（骨科）', 'replacement': '', 'sort_order': 180},
    {'scope': 'scan', 'pattern': '（骨科）（兄）（np）（骨科,古代,性向）', 'replacement': '', 'sort_order': 181},
    {'scope': 'scan', 'pattern': '（骨科）（兄妹）（np）', 'replacement': '', 'sort_order': 182},
    {'scope': 'scan', 'pattern': '（骨科, BDSM）', 'replacement': '', 'sort_order': 183},
    {'scope': 'scan', 'pattern': '（骨科, NP）', 'replacement': '', 'sort_order': 184},
    {'scope': 'scan', 'pattern': '（骨科, 高H）', 'replacement': '', 'sort_order': 185},
    {'scope': 'scan', 'pattern': '(骨科，男男，年上，甜文)', 'replacement': '', 'sort_order': 186},
    {'scope': 'scan', 'pattern': '（海贼王同人）', 'replacement': '', 'sort_order': 187},
    {'scope': 'scan', 'pattern': '(黑道)', 'replacement': '', 'sort_order': 188},
    {'scope': 'scan', 'pattern': '(黑色幽默)', 'replacement': '', 'sort_order': 189},
    {'scope': 'scan', 'pattern': '（黑色幽默, 暗恋, 阴差阳错, 强制爱）', 'replacement': '', 'sort_order': 190},
    {'scope': 'scan', 'pattern': '（黑色幽默, 反乌托邦, 1v1）', 'replacement': '', 'sort_order': 191},
    {'scope': 'scan', 'pattern': '(互攻)', 'replacement': '', 'sort_order': 192},
    {'scope': 'scan', 'pattern': '（互攻）', 'replacement': '', 'sort_order': 193},
    {'scope': 'scan', 'pattern': '（互攻, 1v1）', 'replacement': '', 'sort_order': 194},
    {'scope': 'scan', 'pattern': '（互攻, 直掰弯）', 'replacement': '', 'sort_order': 195},
    {'scope': 'scan', 'pattern': '（幻想空间, 双性, 快穿, NP）', 'replacement': '', 'sort_order': 196},
    {'scope': 'scan', 'pattern': '(荤素均衡)', 'replacement': '', 'sort_order': 197},
    {'scope': 'scan', 'pattern': '（混合性向）', 'replacement': '', 'sort_order': 198},
    {'scope': 'scan', 'pattern': '（混合性向, NP, BDSM, 高H）', 'replacement': '', 'sort_order': 199},
    {'scope': 'scan', 'pattern': '（混合性向, 暗黑, 西方）', 'replacement': '', 'sort_order': 200},
    {'scope': 'scan', 'pattern': '（混合性向, 惊悚, 悬疑, 雷文）', 'replacement': '', 'sort_order': 201},
    {'scope': 'scan', 'pattern': '（混合性向, 美强, 受宠攻, 高H）', 'replacement': '', 'sort_order': 202},
    {'scope': 'scan', 'pattern': '（混合性向, 虐文）', 'replacement': '', 'sort_order': 203},
    {'scope': 'scan', 'pattern': '（混合性向, 双性, NP, 受宠攻）', 'replacement': '', 'sort_order': 204},
    {'scope': 'scan', 'pattern': '（混合性向, 玄幻, 神怪志异）', 'replacement': '', 'sort_order': 205},
    {'scope': 'scan', 'pattern': '(架空世界)', 'replacement': '', 'sort_order': 206},
    {'scope': 'scan', 'pattern': '（架空世界）', 'replacement': '', 'sort_order': 207},
    {'scope': 'scan', 'pattern': '（架空世界, 强制爱, 1v1）', 'replacement': '', 'sort_order': 208},
    {'scope': 'scan', 'pattern': '（架空世界, 强制爱, NP）', 'replacement': '', 'sort_order': 209},
    {'scope': 'scan', 'pattern': '（架空世界, 双性, 高H）', 'replacement': '', 'sort_order': 210},
    {'scope': 'scan', 'pattern': '（架空世界, 双性, 田园乡村）', 'replacement': '', 'sort_order': 211},
    {'scope': 'scan', 'pattern': '（剑三[剑侠情缘网络版三], 混合性向, 互攻）', 'replacement': '', 'sort_order': 212},
    {'scope': 'scan', 'pattern': '（惊悚, 暗黑, 强制爱, NP）', 'replacement': '', 'sort_order': 213},
    {'scope': 'scan', 'pattern': '（惊悚, 骨科）', 'replacement': '', 'sort_order': 214},
    {'scope': 'scan', 'pattern': '（惊悚, 悬疑, 校园）', 'replacement': '', 'sort_order': 215},
    {'scope': 'scan', 'pattern': '(军政)', 'replacement': '', 'sort_order': 216},
    {'scope': 'scan', 'pattern': '（军政）', 'replacement': '', 'sort_order': 217},
    {'scope': 'scan', 'pattern': '（军政, BDSM）', 'replacement': '', 'sort_order': 218},
    {'scope': 'scan', 'pattern': '（军政, 强制爱, 1v1）', 'replacement': '', 'sort_order': 219},
    {'scope': 'scan', 'pattern': '（军政, 日常, 生子）', 'replacement': '', 'sort_order': 220},
    {'scope': 'scan', 'pattern': '(科幻)', 'replacement': '', 'sort_order': 221},
    {'scope': 'scan', 'pattern': '（科幻, ABO, NP）', 'replacement': '', 'sort_order': 222},
    {'scope': 'scan', 'pattern': '（科幻, ABO, 破镜重圆）', 'replacement': '', 'sort_order': 223},
    {'scope': 'scan', 'pattern': '（科幻, 赛博朋克）', 'replacement': '', 'sort_order': 224},
    {'scope': 'scan', 'pattern': '（科幻, 天作之合, 无限流, 互攻）', 'replacement': '', 'sort_order': 225},
    {'scope': 'scan', 'pattern': '（科幻, 相爱相杀）', 'replacement': '', 'sort_order': 226},
    {'scope': 'scan', 'pattern': '(快穿)', 'replacement': '', 'sort_order': 227},
    {'scope': 'scan', 'pattern': '(雷文)', 'replacement': '', 'sort_order': 228},
    {'scope': 'scan', 'pattern': '(连载)', 'replacement': '', 'sort_order': 229},
    {'scope': 'scan', 'pattern': '（灵魂伴侣, 忠犬）', 'replacement': '', 'sort_order': 230},
    {'scope': 'scan', 'pattern': '(灵异)', 'replacement': '', 'sort_order': 231},
    {'scope': 'scan', 'pattern': '（论坛体）', 'replacement': '', 'sort_order': 232},
    {'scope': 'scan', 'pattern': '(美强)', 'replacement': '', 'sort_order': 233},
    {'scope': 'scan', 'pattern': '（美强）', 'replacement': '', 'sort_order': 234},
    {'scope': 'scan', 'pattern': '（美强, 1v1）', 'replacement': '', 'sort_order': 235},
    {'scope': 'scan', 'pattern': '（美强, 生子, 产乳, 高H）', 'replacement': '', 'sort_order': 236},
    {'scope': 'scan', 'pattern': '（美强, 直掰弯, 受宠攻）', 'replacement': '', 'sort_order': 237},
    {'scope': 'scan', 'pattern': '(民国)', 'replacement': '', 'sort_order': 238},
    {'scope': 'scan', 'pattern': '（民国, NP）', 'replacement': '', 'sort_order': 239},
    {'scope': 'scan', 'pattern': '（民国, NTR, 强制爱, NP, 高H）', 'replacement': '', 'sort_order': 240},
    {'scope': 'scan', 'pattern': '（民国, 民俗, NP, 高H）', 'replacement': '', 'sort_order': 241},
    {'scope': 'scan', 'pattern': '（民国, 虐文）', 'replacement': '', 'sort_order': 242},
    {'scope': 'scan', 'pattern': '（民国, 双性, NP）', 'replacement': '', 'sort_order': 243},
    {'scope': 'scan', 'pattern': '（民国, 双性, 高H）', 'replacement': '', 'sort_order': 244},
    {'scope': 'scan', 'pattern': '（民国, 相爱相杀, 强制爱, NP）', 'replacement': '', 'sort_order': 245},
    {'scope': 'scan', 'pattern': '（民俗, NP, 触手）', 'replacement': '', 'sort_order': 246},
    {'scope': 'scan', 'pattern': '（民俗, 骨科）', 'replacement': '', 'sort_order': 247},
    {'scope': 'scan', 'pattern': '（明星[明星], 破镜重圆, 直掰弯）', 'replacement': '', 'sort_order': 248},
    {'scope': 'scan', 'pattern': '（魔法世界, 强制爱, NP, 触手, 高H）', 'replacement': '', 'sort_order': 249},
    {'scope': 'scan', 'pattern': '（魔幻现实, 美强, 弱强）', 'replacement': '', 'sort_order': 250},
    {'scope': 'scan', 'pattern': '（末世, 架空世界）', 'replacement': '', 'sort_order': 251},
    {'scope': 'scan', 'pattern': '（末世, 科幻）', 'replacement': '', 'sort_order': 252},
    {'scope': 'scan', 'pattern': '（末世, 兽人, 公路文, 美强, NP）', 'replacement': '', 'sort_order': 253},
    {'scope': 'scan', 'pattern': '（末世, 双性, NP）', 'replacement': '', 'sort_order': 254},
    {'scope': 'scan', 'pattern': '（脑洞，梗）', 'replacement': '', 'sort_order': 255},
    {'scope': 'scan', 'pattern': '（脑洞番外梗合集）', 'replacement': '', 'sort_order': 256},
    {'scope': 'scan', 'pattern': '(年上)', 'replacement': '', 'sort_order': 257},
    {'scope': 'scan', 'pattern': '(年下)', 'replacement': '', 'sort_order': 258},
    {'scope': 'scan', 'pattern': '(虐文)', 'replacement': '', 'sort_order': 259},
    {'scope': 'scan', 'pattern': '（虐文, 1v1）', 'replacement': '', 'sort_order': 260},
    {'scope': 'scan', 'pattern': '（虐文, ABO）', 'replacement': '', 'sort_order': 261},
    {'scope': 'scan', 'pattern': '（虐文, ABO, 暗恋, NTR, 生子）', 'replacement': '', 'sort_order': 262},
    {'scope': 'scan', 'pattern': '（虐文, 暗黑, 支配服从）', 'replacement': '', 'sort_order': 263},
    {'scope': 'scan', 'pattern': '（虐文, 病娇, 骨科, 高H）', 'replacement': '', 'sort_order': 264},
    {'scope': 'scan', 'pattern': '（虐文, 骨科）', 'replacement': '', 'sort_order': 265},
    {'scope': 'scan', 'pattern': '（虐文, 受宠攻）', 'replacement': '', 'sort_order': 266},
    {'scope': 'scan', 'pattern': '（虐文, 双性, NP, 高H）', 'replacement': '', 'sort_order': 267},
    {'scope': 'scan', 'pattern': '（虐文, 双性, 强制爱）', 'replacement': '', 'sort_order': 268},
    {'scope': 'scan', 'pattern': '(女王)', 'replacement': '', 'sort_order': 269},
    {'scope': 'scan', 'pattern': '(破镜重圆)', 'replacement': '', 'sort_order': 270},
    {'scope': 'scan', 'pattern': '（破镜重圆）', 'replacement': '', 'sort_order': 271},
    {'scope': 'scan', 'pattern': '（破镜重圆, 1v1）', 'replacement': '', 'sort_order': 272},
    {'scope': 'scan', 'pattern': '（破镜重圆, PTSD, 弱强, 受宠攻）', 'replacement': '', 'sort_order': 273},
    {'scope': 'scan', 'pattern': '（破镜重圆, 高H）', 'replacement': '', 'sort_order': 274},
    {'scope': 'scan', 'pattern': '（破镜重圆, 骨科）', 'replacement': '', 'sort_order': 275},
    {'scope': 'scan', 'pattern': '（破镜重圆, 骨科, 1v1）', 'replacement': '', 'sort_order': 276},
    {'scope': 'scan', 'pattern': '（破镜重圆, 强制爱）', 'replacement': '', 'sort_order': 277},
    {'scope': 'scan', 'pattern': '(其他原创)', 'replacement': '', 'sort_order': 278},
    {'scope': 'scan', 'pattern': '(奇幻)', 'replacement': '', 'sort_order': 279},
    {'scope': 'scan', 'pattern': '（奇幻）', 'replacement': '', 'sort_order': 280},
    {'scope': 'scan', 'pattern': '（奇幻, NP, 互攻, 高H）', 'replacement': '', 'sort_order': 281},
    {'scope': 'scan', 'pattern': '（奇幻, 美强, NP）', 'replacement': '', 'sort_order': 282},
    {'scope': 'scan', 'pattern': '（奇幻, 民俗）', 'replacement': '', 'sort_order': 283},
    {'scope': 'scan', 'pattern': '（奇幻, 魔法世界）', 'replacement': '', 'sort_order': 284},
    {'scope': 'scan', 'pattern': '（奇幻, 爽文, 魔法世界, NP）', 'replacement': '', 'sort_order': 285},
    {'scope': 'scan', 'pattern': '（奇幻, 西方, NTR, 生子, 高H）', 'replacement': '', 'sort_order': 286},
    {'scope': 'scan', 'pattern': '（奇幻, 西方, 互攻, 高H）', 'replacement': '', 'sort_order': 287},
    {'scope': 'scan', 'pattern': '（奇幻, 西方, 美强, 生子, 产乳）', 'replacement': '', 'sort_order': 288},
    {'scope': 'scan', 'pattern': '（奇幻, 血族, 1v1）', 'replacement': '', 'sort_order': 289},
    {'scope': 'scan', 'pattern': '（奇幻, 因缘邂逅）', 'replacement': '', 'sort_order': 290},
    {'scope': 'scan', 'pattern': '（前世今生, 破镜重圆）', 'replacement': '', 'sort_order': 291},
    {'scope': 'scan', 'pattern': '（前世今生, 强制爱, NP）', 'replacement': '', 'sort_order': 292},
    {'scope': 'scan', 'pattern': '(强强)', 'replacement': '', 'sort_order': 293},
    {'scope': 'scan', 'pattern': '(强弱)', 'replacement': '', 'sort_order': 294},
    {'scope': 'scan', 'pattern': '(强制爱)', 'replacement': '', 'sort_order': 295},
    {'scope': 'scan', 'pattern': '（强制爱）', 'replacement': '', 'sort_order': 296},
    {'scope': 'scan', 'pattern': '（强制爱, 1v1）', 'replacement': '', 'sort_order': 297},
    {'scope': 'scan', 'pattern': '（强制爱, NP）', 'replacement': '', 'sort_order': 298},
    {'scope': 'scan', 'pattern': '（强制爱, NP, 高H）', 'replacement': '', 'sort_order': 299},
    {'scope': 'scan', 'pattern': '（强制爱, NP, 直掰弯, BDSM, 高H）', 'replacement': '', 'sort_order': 300},
    {'scope': 'scan', 'pattern': '（强制爱, 克系, 触手, 高H）', 'replacement': '', 'sort_order': 301},
    {'scope': 'scan', 'pattern': '（强制爱, 弱强, NP）', 'replacement': '', 'sort_order': 302},
    {'scope': 'scan', 'pattern': '（强制爱, 上下级）', 'replacement': '', 'sort_order': 303},
    {'scope': 'scan', 'pattern': '(青梅竹马)', 'replacement': '', 'sort_order': 304},
    {'scope': 'scan', 'pattern': '(轻松)', 'replacement': '', 'sort_order': 305},
    {'scope': 'scan', 'pattern': '(清水)', 'replacement': '', 'sort_order': 306},
    {'scope': 'scan', 'pattern': '（求票）', 'replacement': '', 'sort_order': 307},
    {'scope': 'scan', 'pattern': '(人鱼)', 'replacement': '', 'sort_order': 308},
    {'scope': 'scan', 'pattern': '（日常）', 'replacement': '', 'sort_order': 309},
    {'scope': 'scan', 'pattern': '（日常, 1v1）', 'replacement': '', 'sort_order': 310},
    {'scope': 'scan', 'pattern': '（日常, 骨科, 1v1）', 'replacement': '', 'sort_order': 311},
    {'scope': 'scan', 'pattern': '（日常, 生子）', 'replacement': '', 'sort_order': 312},
    {'scope': 'scan', 'pattern': '（日常, 天作之合, 1v1）', 'replacement': '', 'sort_order': 313},
    {'scope': 'scan', 'pattern': '（日常, 相爱相杀, 上下级）', 'replacement': '', 'sort_order': 314},
    {'scope': 'scan', 'pattern': '（肉渣）', 'replacement': '', 'sort_order': 315},
    {'scope': 'scan', 'pattern': '(弱强)', 'replacement': '', 'sort_order': 316},
    {'scope': 'scan', 'pattern': '（弱强）', 'replacement': '', 'sort_order': 317},
    {'scope': 'scan', 'pattern': '（弱强, 1v1）', 'replacement': '', 'sort_order': 318},
    {'scope': 'scan', 'pattern': '（弱强, 骨科, 受宠攻）', 'replacement': '', 'sort_order': 319},
    {'scope': 'scan', 'pattern': '（弱强, 受宠攻）', 'replacement': '', 'sort_order': 320},
    {'scope': 'scan', 'pattern': '（弱强, 直掰弯）', 'replacement': '', 'sort_order': 321},
    {'scope': 'scan', 'pattern': '(三观不正)', 'replacement': '', 'sort_order': 322},
    {'scope': 'scan', 'pattern': '(商战)', 'replacement': '', 'sort_order': 323},
    {'scope': 'scan', 'pattern': '（哨兵向导, NP）', 'replacement': '', 'sort_order': 324},
    {'scope': 'scan', 'pattern': '（神怪志异, ABO, 触手）', 'replacement': '', 'sort_order': 325},
    {'scope': 'scan', 'pattern': '（神怪志异, 破镜重圆）', 'replacement': '', 'sort_order': 326},
    {'scope': 'scan', 'pattern': '（神怪志异, 因缘邂逅, 1v1）', 'replacement': '', 'sort_order': 327},
    {'scope': 'scan', 'pattern': '(生子)', 'replacement': '', 'sort_order': 328},
    {'scope': 'scan', 'pattern': '（生子, 受宠攻）', 'replacement': '', 'sort_order': 329},
    {'scope': 'scan', 'pattern': '(师生)', 'replacement': '', 'sort_order': 330},
    {'scope': 'scan', 'pattern': '（师生, NP, 互攻）', 'replacement': '', 'sort_order': 331},
    {'scope': 'scan', 'pattern': '(受宠攻)', 'replacement': '', 'sort_order': 332},
    {'scope': 'scan', 'pattern': '（受宠攻）', 'replacement': '', 'sort_order': 333},
    {'scope': 'scan', 'pattern': '(受受)', 'replacement': '', 'sort_order': 334},
    {'scope': 'scan', 'pattern': '(双性)', 'replacement': '', 'sort_order': 335},
    {'scope': 'scan', 'pattern': '（双性）', 'replacement': '', 'sort_order': 336},
    {'scope': 'scan', 'pattern': '（双性, 1v1）', 'replacement': '', 'sort_order': 337},
    {'scope': 'scan', 'pattern': '（双性, 1v1, 高H）', 'replacement': '', 'sort_order': 338},
    {'scope': 'scan', 'pattern': '（双性, NP）', 'replacement': '', 'sort_order': 339},
    {'scope': 'scan', 'pattern': '（双性, NP, 高H）', 'replacement': '', 'sort_order': 340},
    {'scope': 'scan', 'pattern': '（双性, NTR）', 'replacement': '', 'sort_order': 341},
    {'scope': 'scan', 'pattern': '（双性, NTR, NP）', 'replacement': '', 'sort_order': 342},
    {'scope': 'scan', 'pattern': '（双性, NTR, NP, 高H）', 'replacement': '', 'sort_order': 343},
    {'scope': 'scan', 'pattern': '（双性, NTR, 高H）', 'replacement': '', 'sort_order': 344},
    {'scope': 'scan', 'pattern': '（双性, 产乳, BDSM, 高H）', 'replacement': '', 'sort_order': 345},
    {'scope': 'scan', 'pattern': '（双性, 单元剧, 高H）', 'replacement': '', 'sort_order': 346},
    {'scope': 'scan', 'pattern': '（双性, 父子）', 'replacement': '', 'sort_order': 347},
    {'scope': 'scan', 'pattern': '（双性, 父子, NP）', 'replacement': '', 'sort_order': 348},
    {'scope': 'scan', 'pattern': '（双性, 父子, 高H）', 'replacement': '', 'sort_order': 349},
    {'scope': 'scan', 'pattern': '（双性, 高H）', 'replacement': '', 'sort_order': 350},
    {'scope': 'scan', 'pattern': '（双性, 骨科）', 'replacement': '', 'sort_order': 351},
    {'scope': 'scan', 'pattern': '（双性, 骨科, NP）', 'replacement': '', 'sort_order': 352},
    {'scope': 'scan', 'pattern': '（双性, 互攻, 受受）', 'replacement': '', 'sort_order': 353},
    {'scope': 'scan', 'pattern': '（双性, 克系, NP, 高H）', 'replacement': '', 'sort_order': 354},
    {'scope': 'scan', 'pattern': '（双性, 快穿, NP, 高H）', 'replacement': '', 'sort_order': 355},
    {'scope': 'scan', 'pattern': '（双性, 快穿, 高H）', 'replacement': '', 'sort_order': 356},
    {'scope': 'scan', 'pattern': '（双性, 论坛体, 高H）', 'replacement': '', 'sort_order': 357},
    {'scope': 'scan', 'pattern': '（双性, 美强, 1v1）', 'replacement': '', 'sort_order': 358},
    {'scope': 'scan', 'pattern': '（双性, 美强, NP）', 'replacement': '', 'sort_order': 359},
    {'scope': 'scan', 'pattern': '（双性, 美强, 弱强, 受转攻）', 'replacement': '', 'sort_order': 360},
    {'scope': 'scan', 'pattern': '（双性, 民俗, 产乳, 高H）', 'replacement': '', 'sort_order': 361},
    {'scope': 'scan', 'pattern': '（双性, 破镜重圆）', 'replacement': '', 'sort_order': 362},
    {'scope': 'scan', 'pattern': '（双性, 破镜重圆, 1v1, 高H）', 'replacement': '', 'sort_order': 363},
    {'scope': 'scan', 'pattern': '（双性, 破镜重圆, 高H）', 'replacement': '', 'sort_order': 364},
    {'scope': 'scan', 'pattern': '（双性, 破镜重圆, 强制爱, NP）', 'replacement': '', 'sort_order': 365},
    {'scope': 'scan', 'pattern': '（双性, 破镜重圆, 生子）', 'replacement': '', 'sort_order': 366},
    {'scope': 'scan', 'pattern': '（双性, 前世今生, 无限流, 生子）', 'replacement': '', 'sort_order': 367},
    {'scope': 'scan', 'pattern': '（双性, 强制爱）', 'replacement': '', 'sort_order': 368},
    {'scope': 'scan', 'pattern': '（双性, 强制爱, 1v1, 高H）', 'replacement': '', 'sort_order': 369},
    {'scope': 'scan', 'pattern': '（双性, 强制爱, NP）', 'replacement': '', 'sort_order': 370},
    {'scope': 'scan', 'pattern': '（双性, 强制爱, NP, 高H）', 'replacement': '', 'sort_order': 371},
    {'scope': 'scan', 'pattern': '（双性, 强制爱, 高H）', 'replacement': '', 'sort_order': 372},
    {'scope': 'scan', 'pattern': '（双性, 强制爱, 骨科, 高H）', 'replacement': '', 'sort_order': 373},
    {'scope': 'scan', 'pattern': '（双性, 强制爱, 美强, 生子）', 'replacement': '', 'sort_order': 374},
    {'scope': 'scan', 'pattern': '（双性, 生子）', 'replacement': '', 'sort_order': 375},
    {'scope': 'scan', 'pattern': '（双性, 生子, 1v1）', 'replacement': '', 'sort_order': 376},
    {'scope': 'scan', 'pattern': '（双性, 生子, 1v1, 互攻）', 'replacement': '', 'sort_order': 377},
    {'scope': 'scan', 'pattern': '（双性, 生子, NP）', 'replacement': '', 'sort_order': 378},
    {'scope': 'scan', 'pattern': '（双性, 生子, NP, 高H）', 'replacement': '', 'sort_order': 379},
    {'scope': 'scan', 'pattern': '（双性, 生子, 高H）', 'replacement': '', 'sort_order': 380},
    {'scope': 'scan', 'pattern': '（双性, 生子, 骨科, 高H）', 'replacement': '', 'sort_order': 381},
    {'scope': 'scan', 'pattern': '（双性, 先婚后爱）', 'replacement': '', 'sort_order': 382},
    {'scope': 'scan', 'pattern': '（双性, 相爱相杀, NP, 高H）', 'replacement': '', 'sort_order': 383},
    {'scope': 'scan', 'pattern': '（双性, 校园）', 'replacement': '', 'sort_order': 384},
    {'scope': 'scan', 'pattern': '（双性, 校园, 1v1）', 'replacement': '', 'sort_order': 385},
    {'scope': 'scan', 'pattern': '（双性, 校园, 高H）', 'replacement': '', 'sort_order': 386},
    {'scope': 'scan', 'pattern': '（双性, 校园, 生子）', 'replacement': '', 'sort_order': 387},
    {'scope': 'scan', 'pattern': '（双性, 因缘邂逅, 1v1）', 'replacement': '', 'sort_order': 388},
    {'scope': 'scan', 'pattern': '（双性, 娱乐圈, NTR, 高H）', 'replacement': '', 'sort_order': 389},
    {'scope': 'scan', 'pattern': '（双性, 娱乐圈, 强制爱, BDSM, 高H）', 'replacement': '', 'sort_order': 390},
    {'scope': 'scan', 'pattern': '（双性, 直播, NP）', 'replacement': '', 'sort_order': 391},
    {'scope': 'scan', 'pattern': '（双性, 直播, 师生, 高H）', 'replacement': '', 'sort_order': 392},
    {'scope': 'scan', 'pattern': '（双性, 忠犬）', 'replacement': '', 'sort_order': 393},
    {'scope': 'scan', 'pattern': '（双性, 忠犬, 师生）', 'replacement': '', 'sort_order': 394},
    {'scope': 'scan', 'pattern': '（爽文, 黑道）', 'replacement': '', 'sort_order': 395},
    {'scope': 'scan', 'pattern': '（爽文, 末世, NP）', 'replacement': '', 'sort_order': 396},
    {'scope': 'scan', 'pattern': '（爽文, 玄幻, NP）', 'replacement': '', 'sort_order': 397},
    {'scope': 'scan', 'pattern': '（爽文, 直掰弯）', 'replacement': '', 'sort_order': 398},
    {'scope': 'scan', 'pattern': '（爽文, 重口, BDSM, 高H）', 'replacement': '', 'sort_order': 399},
    {'scope': 'scan', 'pattern': '(天作之合)', 'replacement': '', 'sort_order': 400},
    {'scope': 'scan', 'pattern': '（天作之合, 骨科, 高H）', 'replacement': '', 'sort_order': 401},
    {'scope': 'scan', 'pattern': '（田园乡村, 生子, 1v1）', 'replacement': '', 'sort_order': 402},
    {'scope': 'scan', 'pattern': '（万人迷n）', 'replacement': '', 'sort_order': 403},
    {'scope': 'scan', 'pattern': '（网游, 1v1）', 'replacement': '', 'sort_order': 404},
    {'scope': 'scan', 'pattern': '（网游, 破镜重圆）', 'replacement': '', 'sort_order': 405},
    {'scope': 'scan', 'pattern': '(文艺)', 'replacement': '', 'sort_order': 406},
    {'scope': 'scan', 'pattern': '（文艺, 民俗, NP）', 'replacement': '', 'sort_order': 407},
    {'scope': 'scan', 'pattern': '（文艺, 现实主义, BDSM）', 'replacement': '', 'sort_order': 408},
    {'scope': 'scan', 'pattern': '（无CP）', 'replacement': '', 'sort_order': 409},
    {'scope': 'scan', 'pattern': '（无CP, 科幻, 人工智能）', 'replacement': '', 'sort_order': 410},
    {'scope': 'scan', 'pattern': '(无患子)', 'replacement': '', 'sort_order': 411},
    {'scope': 'scan', 'pattern': '(无限流)', 'replacement': '', 'sort_order': 412},
    {'scope': 'scan', 'pattern': '（无限流, 弱强, 受宠攻）', 'replacement': '', 'sort_order': 413},
    {'scope': 'scan', 'pattern': '(武侠)', 'replacement': '', 'sort_order': 414},
    {'scope': 'scan', 'pattern': '（西方, ABO）', 'replacement': '', 'sort_order': 415},
    {'scope': 'scan', 'pattern': '（西方, 强制爱, 骨科, NP）', 'replacement': '', 'sort_order': 416},
    {'scope': 'scan', 'pattern': '（西方, 养成, 强制爱, 骨科, NP）', 'replacement': '', 'sort_order': 417},
    {'scope': 'scan', 'pattern': '（西方, 战争）', 'replacement': '', 'sort_order': 418},
    {'scope': 'scan', 'pattern': '(喜剧)', 'replacement': '', 'sort_order': 419},
    {'scope': 'scan', 'pattern': '（下克上）', 'replacement': '', 'sort_order': 420},
    {'scope': 'scan', 'pattern': '(仙侠)', 'replacement': '', 'sort_order': 421},
    {'scope': 'scan', 'pattern': '(先婚后爱)', 'replacement': '', 'sort_order': 422},
    {'scope': 'scan', 'pattern': '（先婚后爱）', 'replacement': '', 'sort_order': 423},
    {'scope': 'scan', 'pattern': '（先婚后爱, 强制爱, BDSM）', 'replacement': '', 'sort_order': 424},
    {'scope': 'scan', 'pattern': '（先婚后爱, 生子）', 'replacement': '', 'sort_order': 425},
    {'scope': 'scan', 'pattern': '（先虐攻后虐受，换受）', 'replacement': '', 'sort_order': 426},
    {'scope': 'scan', 'pattern': '(现代)', 'replacement': '', 'sort_order': 427},
    {'scope': 'scan', 'pattern': '（现代1v1）', 'replacement': '', 'sort_order': 428},
    {'scope': 'scan', 'pattern': '（现实主义, 暗黑, 强制爱, NP）', 'replacement': '', 'sort_order': 429},
    {'scope': 'scan', 'pattern': '（现实主义, 相爱相杀）', 'replacement': '', 'sort_order': 430},
    {'scope': 'scan', 'pattern': '（相爱相杀）', 'replacement': '', 'sort_order': 431},
    {'scope': 'scan', 'pattern': '（相爱相杀, 1v1）', 'replacement': '', 'sort_order': 432},
    {'scope': 'scan', 'pattern': '（相爱相杀, 美强）', 'replacement': '', 'sort_order': 433},
    {'scope': 'scan', 'pattern': '（相爱相杀, 美强, 受宠攻）', 'replacement': '', 'sort_order': 434},
    {'scope': 'scan', 'pattern': '（相爱相杀, 破镜重圆）', 'replacement': '', 'sort_order': 435},
    {'scope': 'scan', 'pattern': '（相爱相杀, 强制爱）', 'replacement': '', 'sort_order': 436},
    {'scope': 'scan', 'pattern': '（相爱相杀, 强制爱, 触手, 高H）', 'replacement': '', 'sort_order': 437},
    {'scope': 'scan', 'pattern': '(相爱相杀1v1)', 'replacement': '', 'sort_order': 438},
    {'scope': 'scan', 'pattern': '(小甜饼)', 'replacement': '', 'sort_order': 439},
    {'scope': 'scan', 'pattern': '(校园)', 'replacement': '', 'sort_order': 440},
    {'scope': 'scan', 'pattern': '（校园）', 'replacement': '', 'sort_order': 441},
    {'scope': 'scan', 'pattern': '（校园, 1v1）', 'replacement': '', 'sort_order': 442},
    {'scope': 'scan', 'pattern': '（校园, NP）', 'replacement': '', 'sort_order': 443},
    {'scope': 'scan', 'pattern': '（校园, PTSD, NTR, 病娇）', 'replacement': '', 'sort_order': 444},
    {'scope': 'scan', 'pattern': '（校园, 破镜重圆, 1v1）', 'replacement': '', 'sort_order': 445},
    {'scope': 'scan', 'pattern': '（校园, 破镜重圆, 病娇, 1v1）', 'replacement': '', 'sort_order': 446},
    {'scope': 'scan', 'pattern': '（星际, ABO, 弱强）', 'replacement': '', 'sort_order': 447},
    {'scope': 'scan', 'pattern': '（星际, 虫族, 双性, NP, 高H）', 'replacement': '', 'sort_order': 448},
    {'scope': 'scan', 'pattern': '（星际, 互攻）', 'replacement': '', 'sort_order': 449},
    {'scope': 'scan', 'pattern': '（星际, 奇幻, 科幻, 触手, 德语）', 'replacement': '', 'sort_order': 450},
    {'scope': 'scan', 'pattern': '(玄幻)', 'replacement': '', 'sort_order': 451},
    {'scope': 'scan', 'pattern': '（玄幻, 1v1）', 'replacement': '', 'sort_order': 452},
    {'scope': 'scan', 'pattern': '（玄幻, 前世今生, 破镜重圆）', 'replacement': '', 'sort_order': 453},
    {'scope': 'scan', 'pattern': '（玄幻, 强制爱, NP）', 'replacement': '', 'sort_order': 454},
    {'scope': 'scan', 'pattern': '（玄幻, 升级流, 1v1）', 'replacement': '', 'sort_order': 455},
    {'scope': 'scan', 'pattern': '（玄幻, 双性, NP）', 'replacement': '', 'sort_order': 456},
    {'scope': 'scan', 'pattern': '（玄幻, 相爱相杀）', 'replacement': '', 'sort_order': 457},
    {'scope': 'scan', 'pattern': '（玄幻, 重生, 穿越）', 'replacement': '', 'sort_order': 458},
    {'scope': 'scan', 'pattern': '(悬疑)', 'replacement': '', 'sort_order': 459},
    {'scope': 'scan', 'pattern': '（悬疑, NTR, 强制爱, 病娇）', 'replacement': '', 'sort_order': 460},
    {'scope': 'scan', 'pattern': '（悬疑, 暗黑, NP）', 'replacement': '', 'sort_order': 461},
    {'scope': 'scan', 'pattern': '（悬疑, 黑色幽默, 多重视角, 奇幻, 无限流）', 'replacement': '', 'sort_order': 462},
    {'scope': 'scan', 'pattern': '（悬疑, 哨兵向导, 强制爱, NP）', 'replacement': '', 'sort_order': 463},
    {'scope': 'scan', 'pattern': '（悬疑, 无限流, NP）', 'replacement': '', 'sort_order': 464},
    {'scope': 'scan', 'pattern': '（悬疑, 刑侦）', 'replacement': '', 'sort_order': 465},
    {'scope': 'scan', 'pattern': '(养成)', 'replacement': '', 'sort_order': 466},
    {'scope': 'scan', 'pattern': '（养成, 1v1）', 'replacement': '', 'sort_order': 467},
    {'scope': 'scan', 'pattern': '（养成, BDSM）', 'replacement': '', 'sort_order': 468},
    {'scope': 'scan', 'pattern': '（养成, 病娇, NP）', 'replacement': '', 'sort_order': 469},
    {'scope': 'scan', 'pattern': '（养成, 骨科）', 'replacement': '', 'sort_order': 470},
    {'scope': 'scan', 'pattern': '（养成, 破镜重圆, 骨科）', 'replacement': '', 'sort_order': 471},
    {'scope': 'scan', 'pattern': '（养成, 忠犬, 父子）', 'replacement': '', 'sort_order': 472},
    {'scope': 'scan', 'pattern': '(异能)', 'replacement': '', 'sort_order': 473},
    {'scope': 'scan', 'pattern': '（异能, 系统, 骨科, 1v1）', 'replacement': '', 'sort_order': 474},
    {'scope': 'scan', 'pattern': '（因缘邂逅）', 'replacement': '', 'sort_order': 475},
    {'scope': 'scan', 'pattern': '（因缘邂逅, 1v1）', 'replacement': '', 'sort_order': 476},
    {'scope': 'scan', 'pattern': '（因缘邂逅, 公路文）', 'replacement': '', 'sort_order': 477},
    {'scope': 'scan', 'pattern': '(阴差阳错)', 'replacement': '', 'sort_order': 478},
    {'scope': 'scan', 'pattern': '（阴差阳错, NP）', 'replacement': '', 'sort_order': 479},
    {'scope': 'scan', 'pattern': '（阴差阳错, 强制爱）', 'replacement': '', 'sort_order': 480},
    {'scope': 'scan', 'pattern': '（阴差阳错, 下克上）', 'replacement': '', 'sort_order': 481},
    {'scope': 'scan', 'pattern': '（娱乐圈）', 'replacement': '', 'sort_order': 482},
    {'scope': 'scan', 'pattern': '（娱乐圈, 1v1）', 'replacement': '', 'sort_order': 483},
    {'scope': 'scan', 'pattern': '（娱乐圈, 论坛体）', 'replacement': '', 'sort_order': 484},
    {'scope': 'scan', 'pattern': '（原神[原神], 游戏同人, 悲剧, BE, 生子）', 'replacement': '', 'sort_order': 485},
    {'scope': 'scan', 'pattern': '（原始社会, 双性, 强制爱, 民俗）', 'replacement': '', 'sort_order': 486},
    {'scope': 'scan', 'pattern': '（战争, 相爱相杀, 1v1）', 'replacement': '', 'sort_order': 487},
    {'scope': 'scan', 'pattern': '(长篇)', 'replacement': '', 'sort_order': 488},
    {'scope': 'scan', 'pattern': '(正剧)', 'replacement': '', 'sort_order': 489},
    {'scope': 'scan', 'pattern': '（支配服从, 相爱相杀, 破镜重圆, BDSM）', 'replacement': '', 'sort_order': 490},
    {'scope': 'scan', 'pattern': '（支配服从, 因缘邂逅, 忠犬, 下克上, BDSM）', 'replacement': '', 'sort_order': 491},
    {'scope': 'scan', 'pattern': '(直掰弯)', 'replacement': '', 'sort_order': 492},
    {'scope': 'scan', 'pattern': '（直掰弯）', 'replacement': '', 'sort_order': 493},
    {'scope': 'scan', 'pattern': '(直播)', 'replacement': '', 'sort_order': 494},
    {'scope': 'scan', 'pattern': '（直播, 1v1）', 'replacement': '', 'sort_order': 495},
    {'scope': 'scan', 'pattern': '（直播, NP）', 'replacement': '', 'sort_order': 496},
    {'scope': 'scan', 'pattern': '（直播, 无限流, NP, 高H）', 'replacement': '', 'sort_order': 497},
    {'scope': 'scan', 'pattern': '（职业文）', 'replacement': '', 'sort_order': 498},
    {'scope': 'scan', 'pattern': '（职业文, 互攻）', 'replacement': '', 'sort_order': 499},
    {'scope': 'scan', 'pattern': '(治愈)', 'replacement': '', 'sort_order': 500},
    {'scope': 'scan', 'pattern': '(致郁)', 'replacement': '', 'sort_order': 501},
    {'scope': 'scan', 'pattern': '（中后期高h，正文完结', 'replacement': '', 'sort_order': 502},
    {'scope': 'scan', 'pattern': '(中篇)', 'replacement': '', 'sort_order': 503},
    {'scope': 'scan', 'pattern': '（忠犬, 女王）', 'replacement': '', 'sort_order': 504},
    {'scope': 'scan', 'pattern': '（重口）', 'replacement': '', 'sort_order': 505},
    {'scope': 'scan', 'pattern': '（开新文中)', 'replacement': '', 'sort_order': 506},
    {'scope': 'scan', 'pattern': '（重口, ABO, 先婚后爱, 高H）', 'replacement': '', 'sort_order': 507},
    {'scope': 'scan', 'pattern': '（重口, NTR, 攻转受）', 'replacement': '', 'sort_order': 508},
    {'scope': 'scan', 'pattern': '（重口, 强制爱, 高H）', 'replacement': '', 'sort_order': 509},
    {'scope': 'scan', 'pattern': '（重口, 双性, 强制爱, NP, 高H）', 'replacement': '', 'sort_order': 510},
    {'scope': 'scan', 'pattern': '（重生, NP）', 'replacement': '', 'sort_order': 511},
    {'scope': 'scan', 'pattern': '（重生, 忠犬）', 'replacement': '', 'sort_order': 512},
    {'scope': 'scan', 'pattern': '(主攻视角)', 'replacement': '', 'sort_order': 513},
    {'scope': 'scan', 'pattern': '（主攻星际）', 'replacement': '', 'sort_order': 514},
    {'scope': 'scan', 'pattern': '(宗教)', 'replacement': '', 'sort_order': 515},
    {'scope': 'scan', 'pattern': '(总攻)', 'replacement': '', 'sort_order': 516},
    {'scope': 'scan', 'pattern': '（总攻_NP）', 'replacement': '', 'sort_order': 517},
    {'scope': 'scan', 'pattern': '[BL ]', 'replacement': '', 'sort_order': 518},
    {'scope': 'scan', 'pattern': '[R18G强强虐身]', 'replacement': '', 'sort_order': 519},
    {'scope': 'scan', 'pattern': '[叉糕双性调教]', 'replacement': '', 'sort_order': 520},
    {'scope': 'scan', 'pattern': '[父子伦理cuntboy生子纯爱]', 'replacement': '', 'sort_order': 521},
    {'scope': 'scan', 'pattern': '（1-1强制', 'replacement': '', 'sort_order': 522},
    {'scope': 'scan', 'pattern': '(1v1', 'replacement': '', 'sort_order': 523},
    {'scope': 'scan', 'pattern': '（1v1', 'replacement': '', 'sort_order': 524},
    {'scope': 'scan', 'pattern': '（1v1, 高H', 'replacement': '', 'sort_order': 525},
    {'scope': 'scan', 'pattern': '（1v1, 直掰弯', 'replacement': '', 'sort_order': 526},
    {'scope': 'scan', 'pattern': '（1v2', 'replacement': '', 'sort_order': 527},
    {'scope': 'scan', 'pattern': '（1vN', 'replacement': '', 'sort_order': 528},
    {'scope': 'scan', 'pattern': '（1vn', 'replacement': '', 'sort_order': 529},
    {'scope': 'scan', 'pattern': '（2025年重修版', 'replacement': '', 'sort_order': 530},
    {'scope': 'scan', 'pattern': '（3P_强制', 'replacement': '', 'sort_order': 531},
    {'scope': 'scan', 'pattern': '(ABO', 'replacement': '', 'sort_order': 532},
    {'scope': 'scan', 'pattern': '（ABO', 'replacement': '', 'sort_order': 533},
    {'scope': 'scan', 'pattern': '（ABO, 1v1', 'replacement': '', 'sort_order': 534},
    {'scope': 'scan', 'pattern': '（ABO, NP', 'replacement': '', 'sort_order': 535},
    {'scope': 'scan', 'pattern': '（ABO, 穿越, 生子', 'replacement': '', 'sort_order': 536},
    {'scope': 'scan', 'pattern': '（ABO, 高H', 'replacement': '', 'sort_order': 537},
    {'scope': 'scan', 'pattern': '（ABO, 骨科', 'replacement': '', 'sort_order': 538},
    {'scope': 'scan', 'pattern': '（ABO, 破镜重圆', 'replacement': '', 'sort_order': 539},
    {'scope': 'scan', 'pattern': '（ABO, 破镜重圆, 骨科', 'replacement': '', 'sort_order': 540},
    {'scope': 'scan', 'pattern': '（ABO, 破镜重圆, 生子', 'replacement': '', 'sort_order': 541},
    {'scope': 'scan', 'pattern': '（ABO, 强制爱, NP, 高H', 'replacement': '', 'sort_order': 542},
    {'scope': 'scan', 'pattern': '（ABO, 强制爱, 骨科, NP', 'replacement': '', 'sort_order': 543},
    {'scope': 'scan', 'pattern': '（ABO, 强制爱, 美强', 'replacement': '', 'sort_order': 544},
    {'scope': 'scan', 'pattern': '（ABO, 强制爱, 异能', 'replacement': '', 'sort_order': 545},
    {'scope': 'scan', 'pattern': '（ABO, 弱强, 受宠攻', 'replacement': '', 'sort_order': 546},
    {'scope': 'scan', 'pattern': '（ABO, 生子', 'replacement': '', 'sort_order': 547},
    {'scope': 'scan', 'pattern': '（ABO, 生子, 高H', 'replacement': '', 'sort_order': 548},
    {'scope': 'scan', 'pattern': '（ABO, 双性, NP', 'replacement': '', 'sort_order': 549},
    {'scope': 'scan', 'pattern': '（ABO, 双性, 高H', 'replacement': '', 'sort_order': 550},
    {'scope': 'scan', 'pattern': '（ABO, 双性, 生子, 产乳', 'replacement': '', 'sort_order': 551},
    {'scope': 'scan', 'pattern': '（ABO, 天作之合, 1v1', 'replacement': '', 'sort_order': 552},
    {'scope': 'scan', 'pattern': '（ABO, 西方, 强制爱, NP', 'replacement': '', 'sort_order': 553},
    {'scope': 'scan', 'pattern': '（ABO, 先婚后爱', 'replacement': '', 'sort_order': 554},
    {'scope': 'scan', 'pattern': '（ABO, 先婚后爱, 高H', 'replacement': '', 'sort_order': 555},
    {'scope': 'scan', 'pattern': '（ABO, 先婚后爱, 互攻', 'replacement': '', 'sort_order': 556},
    {'scope': 'scan', 'pattern': '（ABO, 先婚后爱, 强制爱', 'replacement': '', 'sort_order': 557},
    {'scope': 'scan', 'pattern': '（ABO, 相爱相杀, 生子, 高H', 'replacement': '', 'sort_order': 558},
    {'scope': 'scan', 'pattern': '（ABO, 阴差阳错, NTR, NP', 'replacement': '', 'sort_order': 559},
    {'scope': 'scan', 'pattern': '（ABO, 娱乐圈, 暗恋, 重生', 'replacement': '', 'sort_order': 560},
    {'scope': 'scan', 'pattern': '（ABO, 娱乐圈, 强制爱', 'replacement': '', 'sort_order': 561},
    {'scope': 'scan', 'pattern': '（ABO强制爱_all橘', 'replacement': '', 'sort_order': 562},
    {'scope': 'scan', 'pattern': '(BDSM', 'replacement': '', 'sort_order': 563},
    {'scope': 'scan', 'pattern': '（BDSM', 'replacement': '', 'sort_order': 564},
    {'scope': 'scan', 'pattern': '（BE, 美强', 'replacement': '', 'sort_order': 565},
    {'scope': 'scan', 'pattern': '（BE, 强制爱, NP', 'replacement': '', 'sort_order': 566},
    {'scope': 'scan', 'pattern': '（BE, 校园', 'replacement': '', 'sort_order': 567},
    {'scope': 'scan', 'pattern': '(Ending', 'replacement': '', 'sort_order': 568},
    {'scope': 'scan', 'pattern': '（futa np', 'replacement': '', 'sort_order': 569},
    {'scope': 'scan', 'pattern': '（H_C, 暗黑, MB', 'replacement': '', 'sort_order': 570},
    {'scope': 'scan', 'pattern': '（H_C, 暗恋', 'replacement': '', 'sort_order': 571},
    {'scope': 'scan', 'pattern': '（H_C, 黑色幽默, 美强', 'replacement': '', 'sort_order': 572},
    {'scope': 'scan', 'pattern': '（H_C, 美强, NP', 'replacement': '', 'sort_order': 573},
    {'scope': 'scan', 'pattern': '（H_C, 日系, 破镜重圆', 'replacement': '', 'sort_order': 574},
    {'scope': 'scan', 'pattern': '（H_C, 哨兵向导, 1v1', 'replacement': '', 'sort_order': 575},
    {'scope': 'scan', 'pattern': '（H_C, 双性, 破镜重圆', 'replacement': '', 'sort_order': 576},
    {'scope': 'scan', 'pattern': '（H_C, 西方, 强制爱, 高H', 'replacement': '', 'sort_order': 577},
    {'scope': 'scan', 'pattern': '(Happy', 'replacement': '', 'sort_order': 578},
    {'scope': 'scan', 'pattern': '（MB', 'replacement': '', 'sort_order': 579},
    {'scope': 'scan', 'pattern': '（n', 'replacement': '', 'sort_order': 580},
    {'scope': 'scan', 'pattern': '(NP', 'replacement': '', 'sort_order': 581},
    {'scope': 'scan', 'pattern': '（NP', 'replacement': '', 'sort_order': 582},
    {'scope': 'scan', 'pattern': '（NP, BDSM', 'replacement': '', 'sort_order': 583},
    {'scope': 'scan', 'pattern': '（NP, 高H', 'replacement': '', 'sort_order': 584},
    {'scope': 'scan', 'pattern': '（NP, 直掰弯', 'replacement': '', 'sort_order': 585},
    {'scope': 'scan', 'pattern': '(NTR', 'replacement': '', 'sort_order': 586},
    {'scope': 'scan', 'pattern': '（NTR', 'replacement': '', 'sort_order': 587},
    {'scope': 'scan', 'pattern': '（NTR, 父子', 'replacement': '', 'sort_order': 588},
    {'scope': 'scan', 'pattern': '（NTR, 论坛体, 高H', 'replacement': '', 'sort_order': 589},
    {'scope': 'scan', 'pattern': '（NTR, 强制爱', 'replacement': '', 'sort_order': 590},
    {'scope': 'scan', 'pattern': '（OE', 'replacement': '', 'sort_order': 591},
    {'scope': 'scan', 'pattern': '（OE, 骨科, NP, 高H', 'replacement': '', 'sort_order': 592},
    {'scope': 'scan', 'pattern': '（OE, 惊悚, 美强', 'replacement': '', 'sort_order': 593},
    {'scope': 'scan', 'pattern': '（OE, 开放关系', 'replacement': '', 'sort_order': 594},
    {'scope': 'scan', 'pattern': '（OE, 星际, ABO', 'replacement': '', 'sort_order': 595},
    {'scope': 'scan', 'pattern': '(Open', 'replacement': '', 'sort_order': 596},
    {'scope': 'scan', 'pattern': '（PTSD, 强制爱', 'replacement': '', 'sort_order': 597},
    {'scope': 'scan', 'pattern': '(SP _ BDSM', 'replacement': '', 'sort_order': 598},
    {'scope': 'scan', 'pattern': '（sp', 'replacement': '', 'sort_order': 599},
    {'scope': 'scan', 'pattern': '（SP训诫', 'replacement': '', 'sort_order': 600},
    {'scope': 'scan', 'pattern': '(暧昧', 'replacement': '', 'sort_order': 601},
    {'scope': 'scan', 'pattern': '(暗黑', 'replacement': '', 'sort_order': 602},
    {'scope': 'scan', 'pattern': '（暗黑, ABO, 骨科', 'replacement': '', 'sort_order': 603},
    {'scope': 'scan', 'pattern': '（暗黑, 骨科, 下克上, BDSM', 'replacement': '', 'sort_order': 604},
    {'scope': 'scan', 'pattern': '（暗黑, 强制爱, 1v1, 触手', 'replacement': '', 'sort_order': 605},
    {'scope': 'scan', 'pattern': '（暗黑, 强制爱, BDSM', 'replacement': '', 'sort_order': 606},
    {'scope': 'scan', 'pattern': '（暗黑, 强制爱, NP', 'replacement': '', 'sort_order': 607},
    {'scope': 'scan', 'pattern': '（暗黑, 双性', 'replacement': '', 'sort_order': 608},
    {'scope': 'scan', 'pattern': '（暗黑, 双性, 前世今生, 无限流', 'replacement': '', 'sort_order': 609},
    {'scope': 'scan', 'pattern': '（暗黑, 重口, 高H', 'replacement': '', 'sort_order': 610},
    {'scope': 'scan', 'pattern': '(暗恋', 'replacement': '', 'sort_order': 611},
    {'scope': 'scan', 'pattern': '（暗恋', 'replacement': '', 'sort_order': 612},
    {'scope': 'scan', 'pattern': '（暗恋, 1v1', 'replacement': '', 'sort_order': 613},
    {'scope': 'scan', 'pattern': '（暗恋, NP', 'replacement': '', 'sort_order': 614},
    {'scope': 'scan', 'pattern': '（暗恋, 天作之合, 互攻', 'replacement': '', 'sort_order': 615},
    {'scope': 'scan', 'pattern': '（暗恋, 异能', 'replacement': '', 'sort_order': 616},
    {'scope': 'scan', 'pattern': '（暗恋, 忠犬', 'replacement': '', 'sort_order': 617},
    {'scope': 'scan', 'pattern': '（暗恋, 重生', 'replacement': '', 'sort_order': 618},
    {'scope': 'scan', 'pattern': '（悲剧, BE', 'replacement': '', 'sort_order': 619},
    {'scope': 'scan', 'pattern': '（悲剧, BE, 现实主义', 'replacement': '', 'sort_order': 620},
    {'scope': 'scan', 'pattern': '（被螃蟹扛著的鱼', 'replacement': '', 'sort_order': 621},
    {'scope': 'scan', 'pattern': '(产乳', 'replacement': '', 'sort_order': 622},
    {'scope': 'scan', 'pattern': '(虫族', 'replacement': '', 'sort_order': 623},
    {'scope': 'scan', 'pattern': '（虫族, 双性, 生子, 产乳, 高H', 'replacement': '', 'sort_order': 624},
    {'scope': 'scan', 'pattern': '（穿越, NP', 'replacement': '', 'sort_order': 625},
    {'scope': 'scan', 'pattern': '（穿越, 系统, 美强, 1v1', 'replacement': '', 'sort_order': 626},
    {'scope': 'scan', 'pattern': '(大纲', 'replacement': '', 'sort_order': 627},
    {'scope': 'scan', 'pattern': '（大纲, 强制爱, NP', 'replacement': '', 'sort_order': 628},
    {'scope': 'scan', 'pattern': '(大古代', 'replacement': '', 'sort_order': 629},
    {'scope': 'scan', 'pattern': '(大未来', 'replacement': '', 'sort_order': 630},
    {'scope': 'scan', 'pattern': '(大现代', 'replacement': '', 'sort_order': 631},
    {'scope': 'scan', 'pattern': '(大长篇', 'replacement': '', 'sort_order': 632},
    {'scope': 'scan', 'pattern': '(大主受视角', 'replacement': '', 'sort_order': 633},
    {'scope': 'scan', 'pattern': '（第二部', 'replacement': '', 'sort_order': 634},
    {'scope': 'scan', 'pattern': '（暂时缓更版', 'replacement': '', 'sort_order': 635},
    {'scope': 'scan', 'pattern': '(第三人称', 'replacement': '', 'sort_order': 636},
    {'scope': 'scan', 'pattern': '(第一人称', 'replacement': '', 'sort_order': 637},
    {'scope': 'scan', 'pattern': '（东南亚, 天作之合', 'replacement': '', 'sort_order': 638},
    {'scope': 'scan', 'pattern': '（动物世界, 双性, NP, 人兽, 高H', 'replacement': '', 'sort_order': 639},
    {'scope': 'scan', 'pattern': '(短篇', 'replacement': '', 'sort_order': 640},
    {'scope': 'scan', 'pattern': '(多CP高H双男主', 'replacement': '', 'sort_order': 641},
    {'scope': 'scan', 'pattern': '（多重视角, 1v1', 'replacement': '', 'sort_order': 642},
    {'scope': 'scan', 'pattern': '（父子', 'replacement': '', 'sort_order': 643},
    {'scope': 'scan', 'pattern': '（父子, 1v1', 'replacement': '', 'sort_order': 644},
    {'scope': 'scan', 'pattern': '（父子, 高H', 'replacement': '', 'sort_order': 645},
    {'scope': 'scan', 'pattern': '(高H', 'replacement': '', 'sort_order': 646},
    {'scope': 'scan', 'pattern': '（各种炖肉', 'replacement': '', 'sort_order': 647},
    {'scope': 'scan', 'pattern': '（公路文', 'replacement': '', 'sort_order': 648},
    {'scope': 'scan', 'pattern': '(攻宠受', 'replacement': '', 'sort_order': 649},
    {'scope': 'scan', 'pattern': '(宫廷侯爵', 'replacement': '', 'sort_order': 650},
    {'scope': 'scan', 'pattern': '(狗血', 'replacement': '', 'sort_order': 651},
    {'scope': 'scan', 'pattern': '(古代', 'replacement': '', 'sort_order': 652},
    {'scope': 'scan', 'pattern': '(骨科', 'replacement': '', 'sort_order': 653},
    {'scope': 'scan', 'pattern': '（骨科', 'replacement': '', 'sort_order': 654},
    {'scope': 'scan', 'pattern': '（兄', 'replacement': '', 'sort_order': 655},
    {'scope': 'scan', 'pattern': '（np', 'replacement': '', 'sort_order': 656},
    {'scope': 'scan', 'pattern': '（骨科,古代,性向', 'replacement': '', 'sort_order': 657},
    {'scope': 'scan', 'pattern': '（兄妹', 'replacement': '', 'sort_order': 658},
    {'scope': 'scan', 'pattern': '（骨科, BDSM', 'replacement': '', 'sort_order': 659},
    {'scope': 'scan', 'pattern': '（骨科, NP', 'replacement': '', 'sort_order': 660},
    {'scope': 'scan', 'pattern': '（骨科, 高H', 'replacement': '', 'sort_order': 661},
    {'scope': 'scan', 'pattern': '(骨科，男男，年上，甜文', 'replacement': '', 'sort_order': 662},
    {'scope': 'scan', 'pattern': '（海贼王同人', 'replacement': '', 'sort_order': 663},
    {'scope': 'scan', 'pattern': '(黑道', 'replacement': '', 'sort_order': 664},
    {'scope': 'scan', 'pattern': '(黑色幽默', 'replacement': '', 'sort_order': 665},
    {'scope': 'scan', 'pattern': '（黑色幽默, 暗恋, 阴差阳错, 强制爱', 'replacement': '', 'sort_order': 666},
    {'scope': 'scan', 'pattern': '（黑色幽默, 反乌托邦, 1v1', 'replacement': '', 'sort_order': 667},
    {'scope': 'scan', 'pattern': '(互攻', 'replacement': '', 'sort_order': 668},
    {'scope': 'scan', 'pattern': '（互攻', 'replacement': '', 'sort_order': 669},
    {'scope': 'scan', 'pattern': '（互攻, 1v1', 'replacement': '', 'sort_order': 670},
    {'scope': 'scan', 'pattern': '（互攻, 直掰弯', 'replacement': '', 'sort_order': 671},
    {'scope': 'scan', 'pattern': '（幻想空间, 双性, 快穿, NP', 'replacement': '', 'sort_order': 672},
    {'scope': 'scan', 'pattern': '(荤素均衡', 'replacement': '', 'sort_order': 673},
    {'scope': 'scan', 'pattern': '（混合性向', 'replacement': '', 'sort_order': 674},
    {'scope': 'scan', 'pattern': '（混合性向, NP, BDSM, 高H', 'replacement': '', 'sort_order': 675},
    {'scope': 'scan', 'pattern': '（混合性向, 暗黑, 西方', 'replacement': '', 'sort_order': 676},
    {'scope': 'scan', 'pattern': '（混合性向, 惊悚, 悬疑, 雷文', 'replacement': '', 'sort_order': 677},
    {'scope': 'scan', 'pattern': '（混合性向, 美强, 受宠攻, 高H', 'replacement': '', 'sort_order': 678},
    {'scope': 'scan', 'pattern': '（混合性向, 虐文', 'replacement': '', 'sort_order': 679},
    {'scope': 'scan', 'pattern': '（混合性向, 双性, NP, 受宠攻', 'replacement': '', 'sort_order': 680},
    {'scope': 'scan', 'pattern': '（混合性向, 玄幻, 神怪志异', 'replacement': '', 'sort_order': 681},
    {'scope': 'scan', 'pattern': '(架空世界', 'replacement': '', 'sort_order': 682},
    {'scope': 'scan', 'pattern': '（架空世界', 'replacement': '', 'sort_order': 683},
    {'scope': 'scan', 'pattern': '（架空世界, 强制爱, 1v1', 'replacement': '', 'sort_order': 684},
    {'scope': 'scan', 'pattern': '（架空世界, 强制爱, NP', 'replacement': '', 'sort_order': 685},
    {'scope': 'scan', 'pattern': '（架空世界, 双性, 高H', 'replacement': '', 'sort_order': 686},
    {'scope': 'scan', 'pattern': '（架空世界, 双性, 田园乡村', 'replacement': '', 'sort_order': 687},
    {'scope': 'scan', 'pattern': '（剑三[剑侠情缘网络版三], 混合性向, 互攻', 'replacement': '', 'sort_order': 688},
    {'scope': 'scan', 'pattern': '（惊悚, 暗黑, 强制爱, NP', 'replacement': '', 'sort_order': 689},
    {'scope': 'scan', 'pattern': '（惊悚, 骨科', 'replacement': '', 'sort_order': 690},
    {'scope': 'scan', 'pattern': '（惊悚, 悬疑, 校园', 'replacement': '', 'sort_order': 691},
    {'scope': 'scan', 'pattern': '(军政', 'replacement': '', 'sort_order': 692},
    {'scope': 'scan', 'pattern': '（军政', 'replacement': '', 'sort_order': 693},
    {'scope': 'scan', 'pattern': '（军政, BDSM', 'replacement': '', 'sort_order': 694},
    {'scope': 'scan', 'pattern': '（军政, 强制爱, 1v1', 'replacement': '', 'sort_order': 695},
    {'scope': 'scan', 'pattern': '（军政, 日常, 生子', 'replacement': '', 'sort_order': 696},
    {'scope': 'scan', 'pattern': '(科幻', 'replacement': '', 'sort_order': 697},
    {'scope': 'scan', 'pattern': '（科幻, ABO, NP', 'replacement': '', 'sort_order': 698},
    {'scope': 'scan', 'pattern': '（科幻, ABO, 破镜重圆', 'replacement': '', 'sort_order': 699},
    {'scope': 'scan', 'pattern': '（科幻, 赛博朋克', 'replacement': '', 'sort_order': 700},
    {'scope': 'scan', 'pattern': '（科幻, 天作之合, 无限流, 互攻', 'replacement': '', 'sort_order': 701},
    {'scope': 'scan', 'pattern': '（科幻, 相爱相杀', 'replacement': '', 'sort_order': 702},
    {'scope': 'scan', 'pattern': '(快穿', 'replacement': '', 'sort_order': 703},
    {'scope': 'scan', 'pattern': '(雷文', 'replacement': '', 'sort_order': 704},
    {'scope': 'scan', 'pattern': '(连载', 'replacement': '', 'sort_order': 705},
    {'scope': 'scan', 'pattern': '（灵魂伴侣, 忠犬', 'replacement': '', 'sort_order': 706},
    {'scope': 'scan', 'pattern': '(灵异', 'replacement': '', 'sort_order': 707},
    {'scope': 'scan', 'pattern': '（论坛体', 'replacement': '', 'sort_order': 708},
    {'scope': 'scan', 'pattern': '(美强', 'replacement': '', 'sort_order': 709},
    {'scope': 'scan', 'pattern': '（美强', 'replacement': '', 'sort_order': 710},
    {'scope': 'scan', 'pattern': '（美强, 1v1', 'replacement': '', 'sort_order': 711},
    {'scope': 'scan', 'pattern': '（美强, 生子, 产乳, 高H', 'replacement': '', 'sort_order': 712},
    {'scope': 'scan', 'pattern': '（美强, 直掰弯, 受宠攻', 'replacement': '', 'sort_order': 713},
    {'scope': 'scan', 'pattern': '(民国', 'replacement': '', 'sort_order': 714},
    {'scope': 'scan', 'pattern': '（民国, NP', 'replacement': '', 'sort_order': 715},
    {'scope': 'scan', 'pattern': '（民国, NTR, 强制爱, NP, 高H', 'replacement': '', 'sort_order': 716},
    {'scope': 'scan', 'pattern': '（民国, 民俗, NP, 高H', 'replacement': '', 'sort_order': 717},
    {'scope': 'scan', 'pattern': '（民国, 虐文', 'replacement': '', 'sort_order': 718},
    {'scope': 'scan', 'pattern': '（民国, 双性, NP', 'replacement': '', 'sort_order': 719},
    {'scope': 'scan', 'pattern': '（民国, 双性, 高H', 'replacement': '', 'sort_order': 720},
    {'scope': 'scan', 'pattern': '（民国, 相爱相杀, 强制爱, NP', 'replacement': '', 'sort_order': 721},
    {'scope': 'scan', 'pattern': '（民俗, NP, 触手', 'replacement': '', 'sort_order': 722},
    {'scope': 'scan', 'pattern': '（民俗, 骨科', 'replacement': '', 'sort_order': 723},
    {'scope': 'scan', 'pattern': '（明星[明星], 破镜重圆, 直掰弯', 'replacement': '', 'sort_order': 724},
    {'scope': 'scan', 'pattern': '（魔法世界, 强制爱, NP, 触手, 高H', 'replacement': '', 'sort_order': 725},
    {'scope': 'scan', 'pattern': '（魔幻现实, 美强, 弱强', 'replacement': '', 'sort_order': 726},
    {'scope': 'scan', 'pattern': '（末世, 架空世界', 'replacement': '', 'sort_order': 727},
    {'scope': 'scan', 'pattern': '（末世, 科幻', 'replacement': '', 'sort_order': 728},
    {'scope': 'scan', 'pattern': '（末世, 兽人, 公路文, 美强, NP', 'replacement': '', 'sort_order': 729},
    {'scope': 'scan', 'pattern': '（末世, 双性, NP', 'replacement': '', 'sort_order': 730},
    {'scope': 'scan', 'pattern': '（脑洞，梗', 'replacement': '', 'sort_order': 731},
    {'scope': 'scan', 'pattern': '（脑洞番外梗合集', 'replacement': '', 'sort_order': 732},
    {'scope': 'scan', 'pattern': '(年上', 'replacement': '', 'sort_order': 733},
    {'scope': 'scan', 'pattern': '(年下', 'replacement': '', 'sort_order': 734},
    {'scope': 'scan', 'pattern': '(虐文', 'replacement': '', 'sort_order': 735},
    {'scope': 'scan', 'pattern': '（虐文, 1v1', 'replacement': '', 'sort_order': 736},
    {'scope': 'scan', 'pattern': '（虐文, ABO', 'replacement': '', 'sort_order': 737},
    {'scope': 'scan', 'pattern': '（虐文, ABO, 暗恋, NTR, 生子', 'replacement': '', 'sort_order': 738},
    {'scope': 'scan', 'pattern': '（虐文, 暗黑, 支配服从', 'replacement': '', 'sort_order': 739},
    {'scope': 'scan', 'pattern': '（虐文, 病娇, 骨科, 高H', 'replacement': '', 'sort_order': 740},
    {'scope': 'scan', 'pattern': '（虐文, 骨科', 'replacement': '', 'sort_order': 741},
    {'scope': 'scan', 'pattern': '（虐文, 受宠攻', 'replacement': '', 'sort_order': 742},
    {'scope': 'scan', 'pattern': '（虐文, 双性, NP, 高H', 'replacement': '', 'sort_order': 743},
    {'scope': 'scan', 'pattern': '（虐文, 双性, 强制爱', 'replacement': '', 'sort_order': 744},
    {'scope': 'scan', 'pattern': '(女王', 'replacement': '', 'sort_order': 745},
    {'scope': 'scan', 'pattern': '(破镜重圆', 'replacement': '', 'sort_order': 746},
    {'scope': 'scan', 'pattern': '（破镜重圆', 'replacement': '', 'sort_order': 747},
    {'scope': 'scan', 'pattern': '（破镜重圆, 1v1', 'replacement': '', 'sort_order': 748},
    {'scope': 'scan', 'pattern': '（破镜重圆, PTSD, 弱强, 受宠攻', 'replacement': '', 'sort_order': 749},
    {'scope': 'scan', 'pattern': '（破镜重圆, 高H', 'replacement': '', 'sort_order': 750},
    {'scope': 'scan', 'pattern': '（破镜重圆, 骨科', 'replacement': '', 'sort_order': 751},
    {'scope': 'scan', 'pattern': '（破镜重圆, 骨科, 1v1', 'replacement': '', 'sort_order': 752},
    {'scope': 'scan', 'pattern': '（破镜重圆, 强制爱', 'replacement': '', 'sort_order': 753},
    {'scope': 'scan', 'pattern': '(其他原创', 'replacement': '', 'sort_order': 754},
    {'scope': 'scan', 'pattern': '(奇幻', 'replacement': '', 'sort_order': 755},
    {'scope': 'scan', 'pattern': '（奇幻', 'replacement': '', 'sort_order': 756},
    {'scope': 'scan', 'pattern': '（奇幻, NP, 互攻, 高H', 'replacement': '', 'sort_order': 757},
    {'scope': 'scan', 'pattern': '（奇幻, 美强, NP', 'replacement': '', 'sort_order': 758},
    {'scope': 'scan', 'pattern': '（奇幻, 民俗', 'replacement': '', 'sort_order': 759},
    {'scope': 'scan', 'pattern': '（奇幻, 魔法世界', 'replacement': '', 'sort_order': 760},
    {'scope': 'scan', 'pattern': '（奇幻, 爽文, 魔法世界, NP', 'replacement': '', 'sort_order': 761},
    {'scope': 'scan', 'pattern': '（奇幻, 西方, NTR, 生子, 高H', 'replacement': '', 'sort_order': 762},
    {'scope': 'scan', 'pattern': '（奇幻, 西方, 互攻, 高H', 'replacement': '', 'sort_order': 763},
    {'scope': 'scan', 'pattern': '（奇幻, 西方, 美强, 生子, 产乳', 'replacement': '', 'sort_order': 764},
    {'scope': 'scan', 'pattern': '（奇幻, 血族, 1v1', 'replacement': '', 'sort_order': 765},
    {'scope': 'scan', 'pattern': '（奇幻, 因缘邂逅', 'replacement': '', 'sort_order': 766},
    {'scope': 'scan', 'pattern': '（前世今生, 破镜重圆', 'replacement': '', 'sort_order': 767},
    {'scope': 'scan', 'pattern': '（前世今生, 强制爱, NP', 'replacement': '', 'sort_order': 768},
    {'scope': 'scan', 'pattern': '(强强', 'replacement': '', 'sort_order': 769},
    {'scope': 'scan', 'pattern': '(强弱', 'replacement': '', 'sort_order': 770},
    {'scope': 'scan', 'pattern': '(强制爱', 'replacement': '', 'sort_order': 771},
    {'scope': 'scan', 'pattern': '（强制爱', 'replacement': '', 'sort_order': 772},
    {'scope': 'scan', 'pattern': '（强制爱, 1v1', 'replacement': '', 'sort_order': 773},
    {'scope': 'scan', 'pattern': '（强制爱, NP', 'replacement': '', 'sort_order': 774},
    {'scope': 'scan', 'pattern': '（强制爱, NP, 高H', 'replacement': '', 'sort_order': 775},
    {'scope': 'scan', 'pattern': '（强制爱, NP, 直掰弯, BDSM, 高H', 'replacement': '', 'sort_order': 776},
    {'scope': 'scan', 'pattern': '（强制爱, 克系, 触手, 高H', 'replacement': '', 'sort_order': 777},
    {'scope': 'scan', 'pattern': '（强制爱, 弱强, NP', 'replacement': '', 'sort_order': 778},
    {'scope': 'scan', 'pattern': '（强制爱, 上下级', 'replacement': '', 'sort_order': 779},
    {'scope': 'scan', 'pattern': '(青梅竹马', 'replacement': '', 'sort_order': 780},
    {'scope': 'scan', 'pattern': '(轻松', 'replacement': '', 'sort_order': 781},
    {'scope': 'scan', 'pattern': '(清水', 'replacement': '', 'sort_order': 782},
    {'scope': 'scan', 'pattern': '（求票', 'replacement': '', 'sort_order': 783},
    {'scope': 'scan', 'pattern': '(人鱼', 'replacement': '', 'sort_order': 784},
    {'scope': 'scan', 'pattern': '（日常', 'replacement': '', 'sort_order': 785},
    {'scope': 'scan', 'pattern': '（日常, 1v1', 'replacement': '', 'sort_order': 786},
    {'scope': 'scan', 'pattern': '（日常, 骨科, 1v1', 'replacement': '', 'sort_order': 787},
    {'scope': 'scan', 'pattern': '（日常, 生子', 'replacement': '', 'sort_order': 788},
    {'scope': 'scan', 'pattern': '（日常, 天作之合, 1v1', 'replacement': '', 'sort_order': 789},
    {'scope': 'scan', 'pattern': '（日常, 相爱相杀, 上下级', 'replacement': '', 'sort_order': 790},
    {'scope': 'scan', 'pattern': '（肉渣', 'replacement': '', 'sort_order': 791},
    {'scope': 'scan', 'pattern': '(弱强', 'replacement': '', 'sort_order': 792},
    {'scope': 'scan', 'pattern': '（弱强', 'replacement': '', 'sort_order': 793},
    {'scope': 'scan', 'pattern': '（弱强, 1v1', 'replacement': '', 'sort_order': 794},
    {'scope': 'scan', 'pattern': '（弱强, 骨科, 受宠攻', 'replacement': '', 'sort_order': 795},
    {'scope': 'scan', 'pattern': '（弱强, 受宠攻', 'replacement': '', 'sort_order': 796},
    {'scope': 'scan', 'pattern': '（弱强, 直掰弯', 'replacement': '', 'sort_order': 797},
    {'scope': 'scan', 'pattern': '(三观不正', 'replacement': '', 'sort_order': 798},
    {'scope': 'scan', 'pattern': '(商战', 'replacement': '', 'sort_order': 799},
    {'scope': 'scan', 'pattern': '（哨兵向导, NP', 'replacement': '', 'sort_order': 800},
    {'scope': 'scan', 'pattern': '（神怪志异, ABO, 触手', 'replacement': '', 'sort_order': 801},
    {'scope': 'scan', 'pattern': '（神怪志异, 破镜重圆', 'replacement': '', 'sort_order': 802},
    {'scope': 'scan', 'pattern': '（神怪志异, 因缘邂逅, 1v1', 'replacement': '', 'sort_order': 803},
    {'scope': 'scan', 'pattern': '(生子', 'replacement': '', 'sort_order': 804},
    {'scope': 'scan', 'pattern': '（生子, 受宠攻', 'replacement': '', 'sort_order': 805},
    {'scope': 'scan', 'pattern': '(师生', 'replacement': '', 'sort_order': 806},
    {'scope': 'scan', 'pattern': '（师生, NP, 互攻', 'replacement': '', 'sort_order': 807},
    {'scope': 'scan', 'pattern': '(受宠攻', 'replacement': '', 'sort_order': 808},
    {'scope': 'scan', 'pattern': '（受宠攻', 'replacement': '', 'sort_order': 809},
    {'scope': 'scan', 'pattern': '(受受', 'replacement': '', 'sort_order': 810},
    {'scope': 'scan', 'pattern': '(双性', 'replacement': '', 'sort_order': 811},
    {'scope': 'scan', 'pattern': '（双性', 'replacement': '', 'sort_order': 812},
    {'scope': 'scan', 'pattern': '（双性, 1v1', 'replacement': '', 'sort_order': 813},
    {'scope': 'scan', 'pattern': '（双性, 1v1, 高H', 'replacement': '', 'sort_order': 814},
    {'scope': 'scan', 'pattern': '（双性, NP', 'replacement': '', 'sort_order': 815},
    {'scope': 'scan', 'pattern': '（双性, NP, 高H', 'replacement': '', 'sort_order': 816},
    {'scope': 'scan', 'pattern': '（双性, NTR', 'replacement': '', 'sort_order': 817},
    {'scope': 'scan', 'pattern': '（双性, NTR, NP', 'replacement': '', 'sort_order': 818},
    {'scope': 'scan', 'pattern': '（双性, NTR, NP, 高H', 'replacement': '', 'sort_order': 819},
    {'scope': 'scan', 'pattern': '（双性, NTR, 高H', 'replacement': '', 'sort_order': 820},
    {'scope': 'scan', 'pattern': '（双性, 产乳, BDSM, 高H', 'replacement': '', 'sort_order': 821},
    {'scope': 'scan', 'pattern': '（双性, 单元剧, 高H', 'replacement': '', 'sort_order': 822},
    {'scope': 'scan', 'pattern': '（双性, 父子', 'replacement': '', 'sort_order': 823},
    {'scope': 'scan', 'pattern': '（双性, 父子, NP', 'replacement': '', 'sort_order': 824},
    {'scope': 'scan', 'pattern': '（双性, 父子, 高H', 'replacement': '', 'sort_order': 825},
    {'scope': 'scan', 'pattern': '（双性, 高H', 'replacement': '', 'sort_order': 826},
    {'scope': 'scan', 'pattern': '（双性, 骨科', 'replacement': '', 'sort_order': 827},
    {'scope': 'scan', 'pattern': '（双性, 骨科, NP', 'replacement': '', 'sort_order': 828},
    {'scope': 'scan', 'pattern': '（双性, 互攻, 受受', 'replacement': '', 'sort_order': 829},
    {'scope': 'scan', 'pattern': '（双性, 克系, NP, 高H', 'replacement': '', 'sort_order': 830},
    {'scope': 'scan', 'pattern': '（双性, 快穿, NP, 高H', 'replacement': '', 'sort_order': 831},
    {'scope': 'scan', 'pattern': '（双性, 快穿, 高H', 'replacement': '', 'sort_order': 832},
    {'scope': 'scan', 'pattern': '（双性, 论坛体, 高H', 'replacement': '', 'sort_order': 833},
    {'scope': 'scan', 'pattern': '（双性, 美强, 1v1', 'replacement': '', 'sort_order': 834},
    {'scope': 'scan', 'pattern': '（双性, 美强, NP', 'replacement': '', 'sort_order': 835},
    {'scope': 'scan', 'pattern': '（双性, 美强, 弱强, 受转攻', 'replacement': '', 'sort_order': 836},
    {'scope': 'scan', 'pattern': '（双性, 民俗, 产乳, 高H', 'replacement': '', 'sort_order': 837},
    {'scope': 'scan', 'pattern': '（双性, 破镜重圆', 'replacement': '', 'sort_order': 838},
    {'scope': 'scan', 'pattern': '（双性, 破镜重圆, 1v1, 高H', 'replacement': '', 'sort_order': 839},
    {'scope': 'scan', 'pattern': '（双性, 破镜重圆, 高H', 'replacement': '', 'sort_order': 840},
    {'scope': 'scan', 'pattern': '（双性, 破镜重圆, 强制爱, NP', 'replacement': '', 'sort_order': 841},
    {'scope': 'scan', 'pattern': '（双性, 破镜重圆, 生子', 'replacement': '', 'sort_order': 842},
    {'scope': 'scan', 'pattern': '（双性, 前世今生, 无限流, 生子', 'replacement': '', 'sort_order': 843},
    {'scope': 'scan', 'pattern': '（双性, 强制爱', 'replacement': '', 'sort_order': 844},
    {'scope': 'scan', 'pattern': '（双性, 强制爱, 1v1, 高H', 'replacement': '', 'sort_order': 845},
    {'scope': 'scan', 'pattern': '（双性, 强制爱, NP', 'replacement': '', 'sort_order': 846},
    {'scope': 'scan', 'pattern': '（双性, 强制爱, NP, 高H', 'replacement': '', 'sort_order': 847},
    {'scope': 'scan', 'pattern': '（双性, 强制爱, 高H', 'replacement': '', 'sort_order': 848},
    {'scope': 'scan', 'pattern': '（双性, 强制爱, 骨科, 高H', 'replacement': '', 'sort_order': 849},
    {'scope': 'scan', 'pattern': '（双性, 强制爱, 美强, 生子', 'replacement': '', 'sort_order': 850},
    {'scope': 'scan', 'pattern': '（双性, 生子', 'replacement': '', 'sort_order': 851},
    {'scope': 'scan', 'pattern': '（双性, 生子, 1v1', 'replacement': '', 'sort_order': 852},
    {'scope': 'scan', 'pattern': '（双性, 生子, 1v1, 互攻', 'replacement': '', 'sort_order': 853},
    {'scope': 'scan', 'pattern': '（双性, 生子, NP', 'replacement': '', 'sort_order': 854},
    {'scope': 'scan', 'pattern': '（双性, 生子, NP, 高H', 'replacement': '', 'sort_order': 855},
    {'scope': 'scan', 'pattern': '（双性, 生子, 高H', 'replacement': '', 'sort_order': 856},
    {'scope': 'scan', 'pattern': '（双性, 生子, 骨科, 高H', 'replacement': '', 'sort_order': 857},
    {'scope': 'scan', 'pattern': '（双性, 先婚后爱', 'replacement': '', 'sort_order': 858},
    {'scope': 'scan', 'pattern': '（双性, 相爱相杀, NP, 高H', 'replacement': '', 'sort_order': 859},
    {'scope': 'scan', 'pattern': '（双性, 校园', 'replacement': '', 'sort_order': 860},
    {'scope': 'scan', 'pattern': '（双性, 校园, 1v1', 'replacement': '', 'sort_order': 861},
    {'scope': 'scan', 'pattern': '（双性, 校园, 高H', 'replacement': '', 'sort_order': 862},
    {'scope': 'scan', 'pattern': '（双性, 校园, 生子', 'replacement': '', 'sort_order': 863},
    {'scope': 'scan', 'pattern': '（双性, 因缘邂逅, 1v1', 'replacement': '', 'sort_order': 864},
    {'scope': 'scan', 'pattern': '（双性, 娱乐圈, NTR, 高H', 'replacement': '', 'sort_order': 865},
    {'scope': 'scan', 'pattern': '（双性, 娱乐圈, 强制爱, BDSM, 高H', 'replacement': '', 'sort_order': 866},
    {'scope': 'scan', 'pattern': '（双性, 直播, NP', 'replacement': '', 'sort_order': 867},
    {'scope': 'scan', 'pattern': '（双性, 直播, 师生, 高H', 'replacement': '', 'sort_order': 868},
    {'scope': 'scan', 'pattern': '（双性, 忠犬', 'replacement': '', 'sort_order': 869},
    {'scope': 'scan', 'pattern': '（双性, 忠犬, 师生', 'replacement': '', 'sort_order': 870},
    {'scope': 'scan', 'pattern': '（爽文, 黑道', 'replacement': '', 'sort_order': 871},
    {'scope': 'scan', 'pattern': '（爽文, 末世, NP', 'replacement': '', 'sort_order': 872},
    {'scope': 'scan', 'pattern': '（爽文, 玄幻, NP', 'replacement': '', 'sort_order': 873},
    {'scope': 'scan', 'pattern': '（爽文, 直掰弯', 'replacement': '', 'sort_order': 874},
    {'scope': 'scan', 'pattern': '（爽文, 重口, BDSM, 高H', 'replacement': '', 'sort_order': 875},
    {'scope': 'scan', 'pattern': '(天作之合', 'replacement': '', 'sort_order': 876},
    {'scope': 'scan', 'pattern': '（天作之合, 骨科, 高H', 'replacement': '', 'sort_order': 877},
    {'scope': 'scan', 'pattern': '（田园乡村, 生子, 1v1', 'replacement': '', 'sort_order': 878},
    {'scope': 'scan', 'pattern': '（万人迷n', 'replacement': '', 'sort_order': 879},
    {'scope': 'scan', 'pattern': '（网游, 1v1', 'replacement': '', 'sort_order': 880},
    {'scope': 'scan', 'pattern': '（网游, 破镜重圆', 'replacement': '', 'sort_order': 881},
    {'scope': 'scan', 'pattern': '(文艺', 'replacement': '', 'sort_order': 882},
    {'scope': 'scan', 'pattern': '（文艺, 民俗, NP', 'replacement': '', 'sort_order': 883},
    {'scope': 'scan', 'pattern': '（文艺, 现实主义, BDSM', 'replacement': '', 'sort_order': 884},
    {'scope': 'scan', 'pattern': '（无CP', 'replacement': '', 'sort_order': 885},
    {'scope': 'scan', 'pattern': '（无CP, 科幻, 人工智能', 'replacement': '', 'sort_order': 886},
    {'scope': 'scan', 'pattern': '(无患子', 'replacement': '', 'sort_order': 887},
    {'scope': 'scan', 'pattern': '(无限流', 'replacement': '', 'sort_order': 888},
    {'scope': 'scan', 'pattern': '（无限流, 弱强, 受宠攻', 'replacement': '', 'sort_order': 889},
    {'scope': 'scan', 'pattern': '(武侠', 'replacement': '', 'sort_order': 890},
    {'scope': 'scan', 'pattern': '（西方, ABO', 'replacement': '', 'sort_order': 891},
    {'scope': 'scan', 'pattern': '（西方, 强制爱, 骨科, NP', 'replacement': '', 'sort_order': 892},
    {'scope': 'scan', 'pattern': '（西方, 养成, 强制爱, 骨科, NP', 'replacement': '', 'sort_order': 893},
    {'scope': 'scan', 'pattern': '（西方, 战争', 'replacement': '', 'sort_order': 894},
    {'scope': 'scan', 'pattern': '(喜剧', 'replacement': '', 'sort_order': 895},
    {'scope': 'scan', 'pattern': '（下克上', 'replacement': '', 'sort_order': 896},
    {'scope': 'scan', 'pattern': '(仙侠', 'replacement': '', 'sort_order': 897},
    {'scope': 'scan', 'pattern': '(先婚后爱', 'replacement': '', 'sort_order': 898},
    {'scope': 'scan', 'pattern': '（先婚后爱', 'replacement': '', 'sort_order': 899},
    {'scope': 'scan', 'pattern': '（先婚后爱, 强制爱, BDSM', 'replacement': '', 'sort_order': 900},
    {'scope': 'scan', 'pattern': '（先婚后爱, 生子', 'replacement': '', 'sort_order': 901},
    {'scope': 'scan', 'pattern': '（先虐攻后虐受，换受', 'replacement': '', 'sort_order': 902},
    {'scope': 'scan', 'pattern': '(现代', 'replacement': '', 'sort_order': 903},
    {'scope': 'scan', 'pattern': '（现代1v1', 'replacement': '', 'sort_order': 904},
    {'scope': 'scan', 'pattern': '（现实主义, 暗黑, 强制爱, NP', 'replacement': '', 'sort_order': 905},
    {'scope': 'scan', 'pattern': '（现实主义, 相爱相杀', 'replacement': '', 'sort_order': 906},
    {'scope': 'scan', 'pattern': '（相爱相杀', 'replacement': '', 'sort_order': 907},
    {'scope': 'scan', 'pattern': '（相爱相杀, 1v1', 'replacement': '', 'sort_order': 908},
    {'scope': 'scan', 'pattern': '（相爱相杀, 美强', 'replacement': '', 'sort_order': 909},
    {'scope': 'scan', 'pattern': '（相爱相杀, 美强, 受宠攻', 'replacement': '', 'sort_order': 910},
    {'scope': 'scan', 'pattern': '（相爱相杀, 破镜重圆', 'replacement': '', 'sort_order': 911},
    {'scope': 'scan', 'pattern': '（相爱相杀, 强制爱', 'replacement': '', 'sort_order': 912},
    {'scope': 'scan', 'pattern': '（相爱相杀, 强制爱, 触手, 高H', 'replacement': '', 'sort_order': 913},
    {'scope': 'scan', 'pattern': '(相爱相杀1v1', 'replacement': '', 'sort_order': 914},
    {'scope': 'scan', 'pattern': '(小甜饼', 'replacement': '', 'sort_order': 915},
    {'scope': 'scan', 'pattern': '(校园', 'replacement': '', 'sort_order': 916},
    {'scope': 'scan', 'pattern': '（校园', 'replacement': '', 'sort_order': 917},
    {'scope': 'scan', 'pattern': '（校园, 1v1', 'replacement': '', 'sort_order': 918},
    {'scope': 'scan', 'pattern': '（校园, NP', 'replacement': '', 'sort_order': 919},
    {'scope': 'scan', 'pattern': '（校园, PTSD, NTR, 病娇', 'replacement': '', 'sort_order': 920},
    {'scope': 'scan', 'pattern': '（校园, 破镜重圆, 1v1', 'replacement': '', 'sort_order': 921},
    {'scope': 'scan', 'pattern': '（校园, 破镜重圆, 病娇, 1v1', 'replacement': '', 'sort_order': 922},
    {'scope': 'scan', 'pattern': '（星际, ABO, 弱强', 'replacement': '', 'sort_order': 923},
    {'scope': 'scan', 'pattern': '（星际, 虫族, 双性, NP, 高H', 'replacement': '', 'sort_order': 924},
    {'scope': 'scan', 'pattern': '（星际, 互攻', 'replacement': '', 'sort_order': 925},
    {'scope': 'scan', 'pattern': '（星际, 奇幻, 科幻, 触手, 德语', 'replacement': '', 'sort_order': 926},
    {'scope': 'scan', 'pattern': '(玄幻', 'replacement': '', 'sort_order': 927},
    {'scope': 'scan', 'pattern': '（玄幻, 1v1', 'replacement': '', 'sort_order': 928},
    {'scope': 'scan', 'pattern': '（玄幻, 前世今生, 破镜重圆', 'replacement': '', 'sort_order': 929},
    {'scope': 'scan', 'pattern': '（玄幻, 强制爱, NP', 'replacement': '', 'sort_order': 930},
    {'scope': 'scan', 'pattern': '（玄幻, 升级流, 1v1', 'replacement': '', 'sort_order': 931},
    {'scope': 'scan', 'pattern': '（玄幻, 双性, NP', 'replacement': '', 'sort_order': 932},
    {'scope': 'scan', 'pattern': '（玄幻, 相爱相杀', 'replacement': '', 'sort_order': 933},
    {'scope': 'scan', 'pattern': '（玄幻, 重生, 穿越', 'replacement': '', 'sort_order': 934},
    {'scope': 'scan', 'pattern': '(悬疑', 'replacement': '', 'sort_order': 935},
    {'scope': 'scan', 'pattern': '（悬疑, NTR, 强制爱, 病娇', 'replacement': '', 'sort_order': 936},
    {'scope': 'scan', 'pattern': '（悬疑, 暗黑, NP', 'replacement': '', 'sort_order': 937},
    {'scope': 'scan', 'pattern': '（悬疑, 黑色幽默, 多重视角, 奇幻, 无限流', 'replacement': '', 'sort_order': 938},
    {'scope': 'scan', 'pattern': '（悬疑, 哨兵向导, 强制爱, NP', 'replacement': '', 'sort_order': 939},
    {'scope': 'scan', 'pattern': '（悬疑, 无限流, NP', 'replacement': '', 'sort_order': 940},
    {'scope': 'scan', 'pattern': '（悬疑, 刑侦', 'replacement': '', 'sort_order': 941},
    {'scope': 'scan', 'pattern': '(养成', 'replacement': '', 'sort_order': 942},
    {'scope': 'scan', 'pattern': '（养成, 1v1', 'replacement': '', 'sort_order': 943},
    {'scope': 'scan', 'pattern': '（养成, BDSM', 'replacement': '', 'sort_order': 944},
    {'scope': 'scan', 'pattern': '（养成, 病娇, NP', 'replacement': '', 'sort_order': 945},
    {'scope': 'scan', 'pattern': '（养成, 骨科', 'replacement': '', 'sort_order': 946},
    {'scope': 'scan', 'pattern': '（养成, 破镜重圆, 骨科', 'replacement': '', 'sort_order': 947},
    {'scope': 'scan', 'pattern': '（养成, 忠犬, 父子', 'replacement': '', 'sort_order': 948},
    {'scope': 'scan', 'pattern': '(异能', 'replacement': '', 'sort_order': 949},
    {'scope': 'scan', 'pattern': '（异能, 系统, 骨科, 1v1', 'replacement': '', 'sort_order': 950},
    {'scope': 'scan', 'pattern': '（因缘邂逅', 'replacement': '', 'sort_order': 951},
    {'scope': 'scan', 'pattern': '（因缘邂逅, 1v1', 'replacement': '', 'sort_order': 952},
    {'scope': 'scan', 'pattern': '（因缘邂逅, 公路文', 'replacement': '', 'sort_order': 953},
    {'scope': 'scan', 'pattern': '(阴差阳错', 'replacement': '', 'sort_order': 954},
    {'scope': 'scan', 'pattern': '（阴差阳错, NP', 'replacement': '', 'sort_order': 955},
    {'scope': 'scan', 'pattern': '（阴差阳错, 强制爱', 'replacement': '', 'sort_order': 956},
    {'scope': 'scan', 'pattern': '（阴差阳错, 下克上', 'replacement': '', 'sort_order': 957},
    {'scope': 'scan', 'pattern': '（娱乐圈', 'replacement': '', 'sort_order': 958},
    {'scope': 'scan', 'pattern': '（娱乐圈, 1v1', 'replacement': '', 'sort_order': 959},
    {'scope': 'scan', 'pattern': '（娱乐圈, 论坛体', 'replacement': '', 'sort_order': 960},
    {'scope': 'scan', 'pattern': '（原神[原神], 游戏同人, 悲剧, BE, 生子', 'replacement': '', 'sort_order': 961},
    {'scope': 'scan', 'pattern': '（原始社会, 双性, 强制爱, 民俗', 'replacement': '', 'sort_order': 962},
    {'scope': 'scan', 'pattern': '（战争, 相爱相杀, 1v1', 'replacement': '', 'sort_order': 963},
    {'scope': 'scan', 'pattern': '(长篇', 'replacement': '', 'sort_order': 964},
    {'scope': 'scan', 'pattern': '(正剧', 'replacement': '', 'sort_order': 965},
    {'scope': 'scan', 'pattern': '（支配服从, 相爱相杀, 破镜重圆, BDSM', 'replacement': '', 'sort_order': 966},
    {'scope': 'scan', 'pattern': '（支配服从, 因缘邂逅, 忠犬, 下克上, BDSM', 'replacement': '', 'sort_order': 967},
    {'scope': 'scan', 'pattern': '(直掰弯', 'replacement': '', 'sort_order': 968},
    {'scope': 'scan', 'pattern': '（直掰弯', 'replacement': '', 'sort_order': 969},
    {'scope': 'scan', 'pattern': '(直播', 'replacement': '', 'sort_order': 970},
    {'scope': 'scan', 'pattern': '（直播, 1v1', 'replacement': '', 'sort_order': 971},
    {'scope': 'scan', 'pattern': '（直播, NP', 'replacement': '', 'sort_order': 972},
    {'scope': 'scan', 'pattern': '（直播, 无限流, NP, 高H', 'replacement': '', 'sort_order': 973},
    {'scope': 'scan', 'pattern': '（职业文', 'replacement': '', 'sort_order': 974},
    {'scope': 'scan', 'pattern': '（职业文, 互攻', 'replacement': '', 'sort_order': 975},
    {'scope': 'scan', 'pattern': '(治愈', 'replacement': '', 'sort_order': 976},
    {'scope': 'scan', 'pattern': '(致郁', 'replacement': '', 'sort_order': 977},
    {'scope': 'scan', 'pattern': '(中篇', 'replacement': '', 'sort_order': 978},
    {'scope': 'scan', 'pattern': '（忠犬, 女王', 'replacement': '', 'sort_order': 979},
    {'scope': 'scan', 'pattern': '（重口', 'replacement': '', 'sort_order': 980},
    {'scope': 'scan', 'pattern': '（开新文中', 'replacement': '', 'sort_order': 981},
    {'scope': 'scan', 'pattern': '（重口, ABO, 先婚后爱, 高H', 'replacement': '', 'sort_order': 982},
    {'scope': 'scan', 'pattern': '（重口, NTR, 攻转受', 'replacement': '', 'sort_order': 983},
    {'scope': 'scan', 'pattern': '（重口, 强制爱, 高H', 'replacement': '', 'sort_order': 984},
    {'scope': 'scan', 'pattern': '（重口, 双性, 强制爱, NP, 高H', 'replacement': '', 'sort_order': 985},
    {'scope': 'scan', 'pattern': '（重生, NP', 'replacement': '', 'sort_order': 986},
    {'scope': 'scan', 'pattern': '（重生, 忠犬', 'replacement': '', 'sort_order': 987},
    {'scope': 'scan', 'pattern': '(主攻视角', 'replacement': '', 'sort_order': 988},
    {'scope': 'scan', 'pattern': '（主攻星际', 'replacement': '', 'sort_order': 989},
    {'scope': 'scan', 'pattern': '(宗教', 'replacement': '', 'sort_order': 990},
    {'scope': 'scan', 'pattern': '(总攻', 'replacement': '', 'sort_order': 991},
    {'scope': 'scan', 'pattern': '（总攻_NP', 'replacement': '', 'sort_order': 992},
    {'scope': 'scan', 'pattern': '【书香门第★九落】', 'replacement': '', 'sort_order': 46},
]


def seed_default_rules(db: Session) -> int:
    """补齐缺失的预置关键词替换规则（幂等）：按 (scope, pattern) 判断，仅插入库中没有的项。

    - 首次为空时整批写入；
    - 后续新增预置项也会自动补进已安装实例，无需清数据；
    - 只动数据库记录，不触碰磁盘上的源文件。
    返回本次新增的条数。
    """
    added = 0
    for rule in DEFAULT_KEYWORD_RULES:
        exists = db.query(KeywordReplaceRule).filter(
            KeywordReplaceRule.scope == rule['scope'],
            KeywordReplaceRule.pattern == rule['pattern'],
        ).first()
        if not exists:
            db.add(KeywordReplaceRule(
                scope=rule['scope'],
                pattern=rule['pattern'],
                replacement=rule['replacement'],
                sort_order=rule['sort_order'],
                enabled=True,
            ))
            added += 1
    if added:
        db.commit()
    return added
