import Foundation

/// 关键词替换工具（对齐 PC 端 backend/keyword_replace.py）。
enum KeywordReplace {
    static let SCOPE_SCAN = "scan"   // 扫描阶段：作用于文件名
    static let SCOPE_PARSE = "parse" // 解析阶段：作用于 书名/作者/进度/来源

    /// 按规则顺序对文本依次执行「精确字符串替换」，pattern 命中即整段替换为 replacement（空串=删除）。
    static func applyRules(_ text: String?, _ rules: [KeywordReplaceRule]) -> String? {
        guard let text = text, !text.isEmpty, !rules.isEmpty else { return text }
        var result = text
        for r in rules where !r.pattern.isEmpty {
            result = result.replacingOccurrences(of: r.pattern, with: r.replacement)
        }
        return result
    }

    /// 预置的默认关键词替换规则（作用域=扫描阶段，作用于文件名）。仅在规则表为空时写入一次。
    static let DEFAULT_KEYWORD_RULES: [KeywordReplaceRule] = [
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "[草2莓]", replacement: "", sortOrder: 1),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "【草2莓", replacement: "", sortOrder: 2),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "【草2莓】", replacement: "", sortOrder: 3),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "[草 莓]", replacement: "", sortOrder: 4),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "【lili】", replacement: "", sortOrder: 6),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（l.i.）", replacement: "", sortOrder: 7),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(l.i.）", replacement: "", sortOrder: 8),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（l.i.)", replacement: "", sortOrder: 9),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(l.i.)", replacement: "", sortOrder: 10),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "..txt", replacement: ".txt", sortOrder: 11),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "【草莓】", replacement: "", sortOrder: 12),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "【草 莓", replacement: "", sortOrder: 13),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "【＋V信kxee6699】", replacement: "", sortOrder: 14),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: ".3167 937770", replacement: "", sortOrder: 15),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "【颜3167 937770", replacement: "", sortOrder: 16),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "【Q主caomeiの企鹅3167 937770】", replacement: "", sortOrder: 17),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "【Q主caomei】", replacement: "", sortOrder: 18),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "_caomeiの企鹅3167 937770_", replacement: "", sortOrder: 19),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "【qzcaomeiの企鹅3167 937770", replacement: "", sortOrder: 22),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: ".QZcaomeiの企鹅3167 937770", replacement: "", sortOrder: 23),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "_caomeiの企鹅3167 937770", replacement: "", sortOrder: 24),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: ".caomeiの企鹅3167 937770", replacement: "", sortOrder: 25),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "の企鹅3167 937770", replacement: "", sortOrder: 26),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "[3167 937770]", replacement: "", sortOrder: 27),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "3167937770", replacement: "", sortOrder: 29),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "_3167 937770", replacement: "", sortOrder: 30),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "【3167 937770]", replacement: "", sortOrder: 32),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "_.txt", replacement: ".txt", sortOrder: 33),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "【昭昭明月BG】", replacement: "", sortOrder: 34),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "【昭昭明月BL】", replacement: "", sortOrder: 35),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "【推荐】", replacement: "", sortOrder: 36),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "【全本校对】", replacement: "", sortOrder: 37),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "【全本精校】", replacement: "", sortOrder: 38),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "【BL】", replacement: "", sortOrder: 39),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "【BG】", replacement: "", sortOrder: 40),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "【YLW】", replacement: "", sortOrder: 41),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "『推』", replacement: "", sortOrder: 42),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "【YLW连载】", replacement: "", sortOrder: 43),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "【棠】", replacement: "", sortOrder: 44),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "【公众号：推文日记】", replacement: "", sortOrder: 45),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（1-1强制）", replacement: "", sortOrder: 47),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(1v1)", replacement: "", sortOrder: 48),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（1v1）", replacement: "", sortOrder: 49),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（1v1, 高H）", replacement: "", sortOrder: 50),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（1v1, 直掰弯）", replacement: "", sortOrder: 51),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（1v2）", replacement: "", sortOrder: 52),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（1vN）", replacement: "", sortOrder: 53),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（1vn）", replacement: "", sortOrder: 54),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（2025年重修版）", replacement: "", sortOrder: 55),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（3P_强制）", replacement: "", sortOrder: 56),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(ABO)", replacement: "", sortOrder: 57),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO）", replacement: "", sortOrder: 58),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO, 1v1）", replacement: "", sortOrder: 59),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO, NP）", replacement: "", sortOrder: 60),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO, 穿越, 生子）", replacement: "", sortOrder: 61),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO, 高H）", replacement: "", sortOrder: 62),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO, 骨科）", replacement: "", sortOrder: 63),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO, 破镜重圆）", replacement: "", sortOrder: 64),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO, 破镜重圆, 骨科）", replacement: "", sortOrder: 65),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO, 破镜重圆, 生子）", replacement: "", sortOrder: 66),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO, 强制爱, NP, 高H）", replacement: "", sortOrder: 67),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO, 强制爱, 骨科, NP）", replacement: "", sortOrder: 68),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO, 强制爱, 美强）", replacement: "", sortOrder: 69),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO, 强制爱, 异能）", replacement: "", sortOrder: 70),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO, 弱强, 受宠攻）", replacement: "", sortOrder: 71),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO, 生子）", replacement: "", sortOrder: 72),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO, 生子, 高H）", replacement: "", sortOrder: 73),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO, 双性, NP）", replacement: "", sortOrder: 74),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO, 双性, 高H）", replacement: "", sortOrder: 75),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO, 双性, 生子, 产乳）", replacement: "", sortOrder: 76),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO, 天作之合, 1v1）", replacement: "", sortOrder: 77),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO, 西方, 强制爱, NP）", replacement: "", sortOrder: 78),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO, 先婚后爱）", replacement: "", sortOrder: 79),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO, 先婚后爱, 高H）", replacement: "", sortOrder: 80),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO, 先婚后爱, 互攻）", replacement: "", sortOrder: 81),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO, 先婚后爱, 强制爱）", replacement: "", sortOrder: 82),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO, 相爱相杀, 生子, 高H）", replacement: "", sortOrder: 83),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO, 阴差阳错, NTR, NP）", replacement: "", sortOrder: 84),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO, 娱乐圈, 暗恋, 重生）", replacement: "", sortOrder: 85),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO, 娱乐圈, 强制爱）", replacement: "", sortOrder: 86),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（ABO强制爱_all橘）", replacement: "", sortOrder: 87),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(BDSM)", replacement: "", sortOrder: 88),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（BDSM）", replacement: "", sortOrder: 89),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（BE, 美强）", replacement: "", sortOrder: 90),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（BE, 强制爱, NP）", replacement: "", sortOrder: 91),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（BE, 校园）", replacement: "", sortOrder: 92),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(Ending)", replacement: "", sortOrder: 93),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（futa np）", replacement: "", sortOrder: 94),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（H_C, 暗黑, MB）", replacement: "", sortOrder: 95),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（H_C, 暗恋）", replacement: "", sortOrder: 96),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（H_C, 黑色幽默, 美强）", replacement: "", sortOrder: 97),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（H_C, 美强, NP）", replacement: "", sortOrder: 98),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（H_C, 日系, 破镜重圆）", replacement: "", sortOrder: 99),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（H_C, 哨兵向导, 1v1）", replacement: "", sortOrder: 100),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（H_C, 双性, 破镜重圆）", replacement: "", sortOrder: 101),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（H_C, 西方, 强制爱, 高H）", replacement: "", sortOrder: 102),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(Happy)", replacement: "", sortOrder: 103),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（MB）", replacement: "", sortOrder: 104),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（n）", replacement: "", sortOrder: 105),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(NP)", replacement: "", sortOrder: 106),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（NP）", replacement: "", sortOrder: 107),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（NP, BDSM）", replacement: "", sortOrder: 108),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（NP, 高H）", replacement: "", sortOrder: 109),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（NP, 直掰弯）", replacement: "", sortOrder: 110),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(NTR)", replacement: "", sortOrder: 111),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（NTR）", replacement: "", sortOrder: 112),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（NTR, 父子）", replacement: "", sortOrder: 113),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（NTR, 论坛体, 高H）", replacement: "", sortOrder: 114),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（NTR, 强制爱）", replacement: "", sortOrder: 115),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（OE）", replacement: "", sortOrder: 116),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（OE, 骨科, NP, 高H）", replacement: "", sortOrder: 117),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（OE, 惊悚, 美强）", replacement: "", sortOrder: 118),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（OE, 开放关系）", replacement: "", sortOrder: 119),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（OE, 星际, ABO）", replacement: "", sortOrder: 120),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(Open)", replacement: "", sortOrder: 121),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（PTSD, 强制爱）", replacement: "", sortOrder: 122),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(SP _ BDSM)", replacement: "", sortOrder: 123),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（sp）", replacement: "", sortOrder: 124),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（SP训诫）", replacement: "", sortOrder: 125),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(暧昧)", replacement: "", sortOrder: 126),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(暗黑)", replacement: "", sortOrder: 127),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（暗黑, ABO, 骨科）", replacement: "", sortOrder: 128),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（暗黑, 骨科, 下克上, BDSM）", replacement: "", sortOrder: 129),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（暗黑, 强制爱, 1v1, 触手）", replacement: "", sortOrder: 130),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（暗黑, 强制爱, BDSM）", replacement: "", sortOrder: 131),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（暗黑, 强制爱, NP）", replacement: "", sortOrder: 132),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（暗黑, 双性）", replacement: "", sortOrder: 133),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（暗黑, 双性, 前世今生, 无限流）", replacement: "", sortOrder: 134),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（暗黑, 重口, 高H）", replacement: "", sortOrder: 135),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(暗恋)", replacement: "", sortOrder: 136),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（暗恋）", replacement: "", sortOrder: 137),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（暗恋, 1v1）", replacement: "", sortOrder: 138),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（暗恋, NP）", replacement: "", sortOrder: 139),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（暗恋, 天作之合, 互攻）", replacement: "", sortOrder: 140),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（暗恋, 异能）", replacement: "", sortOrder: 141),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（暗恋, 忠犬）", replacement: "", sortOrder: 142),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（暗恋, 重生）", replacement: "", sortOrder: 143),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（悲剧, BE）", replacement: "", sortOrder: 144),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（悲剧, BE, 现实主义）", replacement: "", sortOrder: 145),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（被螃蟹扛著的鱼）", replacement: "", sortOrder: 146),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(产乳)", replacement: "", sortOrder: 147),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(虫族)", replacement: "", sortOrder: 148),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（虫族, 双性, 生子, 产乳, 高H）", replacement: "", sortOrder: 149),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（穿越, NP）", replacement: "", sortOrder: 150),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（穿越, 系统, 美强, 1v1）", replacement: "", sortOrder: 151),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(大纲)", replacement: "", sortOrder: 152),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（大纲, 强制爱, NP）", replacement: "", sortOrder: 153),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(大古代)", replacement: "", sortOrder: 154),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(大未来)", replacement: "", sortOrder: 155),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(大现代)", replacement: "", sortOrder: 156),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(大长篇)", replacement: "", sortOrder: 157),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(大主受视角)", replacement: "", sortOrder: 158),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（第二部）", replacement: "", sortOrder: 159),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（暂时缓更版)", replacement: "", sortOrder: 160),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(第三人称)", replacement: "", sortOrder: 161),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(第一人称)", replacement: "", sortOrder: 162),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(第一人称）", replacement: "", sortOrder: 163),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（东南亚, 天作之合）", replacement: "", sortOrder: 164),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（动物世界, 双性, NP, 人兽, 高H）", replacement: "", sortOrder: 165),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(短篇)", replacement: "", sortOrder: 166),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(多CP高H双男主)", replacement: "", sortOrder: 167),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（多重视角, 1v1）", replacement: "", sortOrder: 168),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（父子）", replacement: "", sortOrder: 169),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（父子, 1v1）", replacement: "", sortOrder: 170),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（父子, 高H）", replacement: "", sortOrder: 171),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(高H)", replacement: "", sortOrder: 172),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（各种炖肉）", replacement: "", sortOrder: 173),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（公路文）", replacement: "", sortOrder: 174),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(攻宠受)", replacement: "", sortOrder: 175),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(宫廷侯爵)", replacement: "", sortOrder: 176),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(狗血)", replacement: "", sortOrder: 177),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(古代)", replacement: "", sortOrder: 178),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(骨科)", replacement: "", sortOrder: 179),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（骨科）", replacement: "", sortOrder: 180),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（骨科）（兄）（np）（骨科,古代,性向）", replacement: "", sortOrder: 181),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（骨科）（兄妹）（np）", replacement: "", sortOrder: 182),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（骨科, BDSM）", replacement: "", sortOrder: 183),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（骨科, NP）", replacement: "", sortOrder: 184),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（骨科, 高H）", replacement: "", sortOrder: 185),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(骨科，男男，年上，甜文)", replacement: "", sortOrder: 186),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（海贼王同人）", replacement: "", sortOrder: 187),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(黑道)", replacement: "", sortOrder: 188),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(黑色幽默)", replacement: "", sortOrder: 189),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（黑色幽默, 暗恋, 阴差阳错, 强制爱）", replacement: "", sortOrder: 190),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（黑色幽默, 反乌托邦, 1v1）", replacement: "", sortOrder: 191),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(互攻)", replacement: "", sortOrder: 192),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（互攻）", replacement: "", sortOrder: 193),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（互攻, 1v1）", replacement: "", sortOrder: 194),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（互攻, 直掰弯）", replacement: "", sortOrder: 195),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（幻想空间, 双性, 快穿, NP）", replacement: "", sortOrder: 196),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(荤素均衡)", replacement: "", sortOrder: 197),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（混合性向）", replacement: "", sortOrder: 198),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（混合性向, NP, BDSM, 高H）", replacement: "", sortOrder: 199),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（混合性向, 暗黑, 西方）", replacement: "", sortOrder: 200),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（混合性向, 惊悚, 悬疑, 雷文）", replacement: "", sortOrder: 201),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（混合性向, 美强, 受宠攻, 高H）", replacement: "", sortOrder: 202),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（混合性向, 虐文）", replacement: "", sortOrder: 203),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（混合性向, 双性, NP, 受宠攻）", replacement: "", sortOrder: 204),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（混合性向, 玄幻, 神怪志异）", replacement: "", sortOrder: 205),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(架空世界)", replacement: "", sortOrder: 206),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（架空世界）", replacement: "", sortOrder: 207),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（架空世界, 强制爱, 1v1）", replacement: "", sortOrder: 208),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（架空世界, 强制爱, NP）", replacement: "", sortOrder: 209),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（架空世界, 双性, 高H）", replacement: "", sortOrder: 210),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（架空世界, 双性, 田园乡村）", replacement: "", sortOrder: 211),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（剑三[剑侠情缘网络版三], 混合性向, 互攻）", replacement: "", sortOrder: 212),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（惊悚, 暗黑, 强制爱, NP）", replacement: "", sortOrder: 213),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（惊悚, 骨科）", replacement: "", sortOrder: 214),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（惊悚, 悬疑, 校园）", replacement: "", sortOrder: 215),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(军政)", replacement: "", sortOrder: 216),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（军政）", replacement: "", sortOrder: 217),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（军政, BDSM）", replacement: "", sortOrder: 218),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（军政, 强制爱, 1v1）", replacement: "", sortOrder: 219),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（军政, 日常, 生子）", replacement: "", sortOrder: 220),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(科幻)", replacement: "", sortOrder: 221),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（科幻, ABO, NP）", replacement: "", sortOrder: 222),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（科幻, ABO, 破镜重圆）", replacement: "", sortOrder: 223),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（科幻, 赛博朋克）", replacement: "", sortOrder: 224),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（科幻, 天作之合, 无限流, 互攻）", replacement: "", sortOrder: 225),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（科幻, 相爱相杀）", replacement: "", sortOrder: 226),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(快穿)", replacement: "", sortOrder: 227),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(雷文)", replacement: "", sortOrder: 228),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(连载)", replacement: "", sortOrder: 229),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（灵魂伴侣, 忠犬）", replacement: "", sortOrder: 230),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(灵异)", replacement: "", sortOrder: 231),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（论坛体）", replacement: "", sortOrder: 232),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(美强)", replacement: "", sortOrder: 233),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（美强）", replacement: "", sortOrder: 234),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（美强, 1v1）", replacement: "", sortOrder: 235),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（美强, 生子, 产乳, 高H）", replacement: "", sortOrder: 236),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（美强, 直掰弯, 受宠攻）", replacement: "", sortOrder: 237),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(民国)", replacement: "", sortOrder: 238),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（民国, NP）", replacement: "", sortOrder: 239),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（民国, NTR, 强制爱, NP, 高H）", replacement: "", sortOrder: 240),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（民国, 民俗, NP, 高H）", replacement: "", sortOrder: 241),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（民国, 虐文）", replacement: "", sortOrder: 242),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（民国, 双性, NP）", replacement: "", sortOrder: 243),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（民国, 双性, 高H）", replacement: "", sortOrder: 244),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（民国, 相爱相杀, 强制爱, NP）", replacement: "", sortOrder: 245),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（民俗, NP, 触手）", replacement: "", sortOrder: 246),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（民俗, 骨科）", replacement: "", sortOrder: 247),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（明星[明星], 破镜重圆, 直掰弯）", replacement: "", sortOrder: 248),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（魔法世界, 强制爱, NP, 触手, 高H）", replacement: "", sortOrder: 249),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（魔幻现实, 美强, 弱强）", replacement: "", sortOrder: 250),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（末世, 架空世界）", replacement: "", sortOrder: 251),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（末世, 科幻）", replacement: "", sortOrder: 252),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（末世, 兽人, 公路文, 美强, NP）", replacement: "", sortOrder: 253),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（末世, 双性, NP）", replacement: "", sortOrder: 254),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（脑洞，梗）", replacement: "", sortOrder: 255),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（脑洞番外梗合集）", replacement: "", sortOrder: 256),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(年上)", replacement: "", sortOrder: 257),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(年下)", replacement: "", sortOrder: 258),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(虐文)", replacement: "", sortOrder: 259),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（虐文, 1v1）", replacement: "", sortOrder: 260),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（虐文, ABO）", replacement: "", sortOrder: 261),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（虐文, ABO, 暗恋, NTR, 生子）", replacement: "", sortOrder: 262),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（虐文, 暗黑, 支配服从）", replacement: "", sortOrder: 263),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（虐文, 病娇, 骨科, 高H）", replacement: "", sortOrder: 264),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（虐文, 骨科）", replacement: "", sortOrder: 265),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（虐文, 受宠攻）", replacement: "", sortOrder: 266),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（虐文, 双性, NP, 高H）", replacement: "", sortOrder: 267),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（虐文, 双性, 强制爱）", replacement: "", sortOrder: 268),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(女王)", replacement: "", sortOrder: 269),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(破镜重圆)", replacement: "", sortOrder: 270),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（破镜重圆）", replacement: "", sortOrder: 271),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（破镜重圆, 1v1）", replacement: "", sortOrder: 272),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（破镜重圆, PTSD, 弱强, 受宠攻）", replacement: "", sortOrder: 273),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（破镜重圆, 高H）", replacement: "", sortOrder: 274),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（破镜重圆, 骨科）", replacement: "", sortOrder: 275),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（破镜重圆, 骨科, 1v1）", replacement: "", sortOrder: 276),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（破镜重圆, 强制爱）", replacement: "", sortOrder: 277),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(其他原创)", replacement: "", sortOrder: 278),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(奇幻)", replacement: "", sortOrder: 279),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（奇幻）", replacement: "", sortOrder: 280),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（奇幻, NP, 互攻, 高H）", replacement: "", sortOrder: 281),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（奇幻, 美强, NP）", replacement: "", sortOrder: 282),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（奇幻, 民俗）", replacement: "", sortOrder: 283),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（奇幻, 魔法世界）", replacement: "", sortOrder: 284),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（奇幻, 爽文, 魔法世界, NP）", replacement: "", sortOrder: 285),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（奇幻, 西方, NTR, 生子, 高H）", replacement: "", sortOrder: 286),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（奇幻, 西方, 互攻, 高H）", replacement: "", sortOrder: 287),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（奇幻, 西方, 美强, 生子, 产乳）", replacement: "", sortOrder: 288),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（奇幻, 血族, 1v1）", replacement: "", sortOrder: 289),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（奇幻, 因缘邂逅）", replacement: "", sortOrder: 290),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（前世今生, 破镜重圆）", replacement: "", sortOrder: 291),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（前世今生, 强制爱, NP）", replacement: "", sortOrder: 292),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(强强)", replacement: "", sortOrder: 293),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(强弱)", replacement: "", sortOrder: 294),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(强制爱)", replacement: "", sortOrder: 295),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（强制爱）", replacement: "", sortOrder: 296),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（强制爱, 1v1）", replacement: "", sortOrder: 297),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（强制爱, NP）", replacement: "", sortOrder: 298),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（强制爱, NP, 高H）", replacement: "", sortOrder: 299),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（强制爱, NP, 直掰弯, BDSM, 高H）", replacement: "", sortOrder: 300),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（强制爱, 克系, 触手, 高H）", replacement: "", sortOrder: 301),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（强制爱, 弱强, NP）", replacement: "", sortOrder: 302),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（强制爱, 上下级）", replacement: "", sortOrder: 303),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(青梅竹马)", replacement: "", sortOrder: 304),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(轻松)", replacement: "", sortOrder: 305),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(清水)", replacement: "", sortOrder: 306),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（求票）", replacement: "", sortOrder: 307),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(人鱼)", replacement: "", sortOrder: 308),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（日常）", replacement: "", sortOrder: 309),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（日常, 1v1）", replacement: "", sortOrder: 310),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（日常, 骨科, 1v1）", replacement: "", sortOrder: 311),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（日常, 生子）", replacement: "", sortOrder: 312),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（日常, 天作之合, 1v1）", replacement: "", sortOrder: 313),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（日常, 相爱相杀, 上下级）", replacement: "", sortOrder: 314),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（肉渣）", replacement: "", sortOrder: 315),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(弱强)", replacement: "", sortOrder: 316),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（弱强）", replacement: "", sortOrder: 317),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（弱强, 1v1）", replacement: "", sortOrder: 318),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（弱强, 骨科, 受宠攻）", replacement: "", sortOrder: 319),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（弱强, 受宠攻）", replacement: "", sortOrder: 320),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（弱强, 直掰弯）", replacement: "", sortOrder: 321),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(三观不正)", replacement: "", sortOrder: 322),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(商战)", replacement: "", sortOrder: 323),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（哨兵向导, NP）", replacement: "", sortOrder: 324),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（神怪志异, ABO, 触手）", replacement: "", sortOrder: 325),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（神怪志异, 破镜重圆）", replacement: "", sortOrder: 326),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（神怪志异, 因缘邂逅, 1v1）", replacement: "", sortOrder: 327),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(生子)", replacement: "", sortOrder: 328),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（生子, 受宠攻）", replacement: "", sortOrder: 329),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(师生)", replacement: "", sortOrder: 330),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（师生, NP, 互攻）", replacement: "", sortOrder: 331),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(受宠攻)", replacement: "", sortOrder: 332),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（受宠攻）", replacement: "", sortOrder: 333),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(受受)", replacement: "", sortOrder: 334),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(双性)", replacement: "", sortOrder: 335),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性）", replacement: "", sortOrder: 336),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 1v1）", replacement: "", sortOrder: 337),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 1v1, 高H）", replacement: "", sortOrder: 338),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, NP）", replacement: "", sortOrder: 339),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, NP, 高H）", replacement: "", sortOrder: 340),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, NTR）", replacement: "", sortOrder: 341),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, NTR, NP）", replacement: "", sortOrder: 342),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, NTR, NP, 高H）", replacement: "", sortOrder: 343),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, NTR, 高H）", replacement: "", sortOrder: 344),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 产乳, BDSM, 高H）", replacement: "", sortOrder: 345),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 单元剧, 高H）", replacement: "", sortOrder: 346),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 父子）", replacement: "", sortOrder: 347),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 父子, NP）", replacement: "", sortOrder: 348),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 父子, 高H）", replacement: "", sortOrder: 349),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 高H）", replacement: "", sortOrder: 350),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 骨科）", replacement: "", sortOrder: 351),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 骨科, NP）", replacement: "", sortOrder: 352),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 互攻, 受受）", replacement: "", sortOrder: 353),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 克系, NP, 高H）", replacement: "", sortOrder: 354),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 快穿, NP, 高H）", replacement: "", sortOrder: 355),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 快穿, 高H）", replacement: "", sortOrder: 356),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 论坛体, 高H）", replacement: "", sortOrder: 357),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 美强, 1v1）", replacement: "", sortOrder: 358),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 美强, NP）", replacement: "", sortOrder: 359),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 美强, 弱强, 受转攻）", replacement: "", sortOrder: 360),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 民俗, 产乳, 高H）", replacement: "", sortOrder: 361),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 破镜重圆）", replacement: "", sortOrder: 362),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 破镜重圆, 1v1, 高H）", replacement: "", sortOrder: 363),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 破镜重圆, 高H）", replacement: "", sortOrder: 364),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 破镜重圆, 强制爱, NP）", replacement: "", sortOrder: 365),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 破镜重圆, 生子）", replacement: "", sortOrder: 366),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 前世今生, 无限流, 生子）", replacement: "", sortOrder: 367),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 强制爱）", replacement: "", sortOrder: 368),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 强制爱, 1v1, 高H）", replacement: "", sortOrder: 369),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 强制爱, NP）", replacement: "", sortOrder: 370),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 强制爱, NP, 高H）", replacement: "", sortOrder: 371),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 强制爱, 高H）", replacement: "", sortOrder: 372),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 强制爱, 骨科, 高H）", replacement: "", sortOrder: 373),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 强制爱, 美强, 生子）", replacement: "", sortOrder: 374),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 生子）", replacement: "", sortOrder: 375),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 生子, 1v1）", replacement: "", sortOrder: 376),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 生子, 1v1, 互攻）", replacement: "", sortOrder: 377),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 生子, NP）", replacement: "", sortOrder: 378),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 生子, NP, 高H）", replacement: "", sortOrder: 379),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 生子, 高H）", replacement: "", sortOrder: 380),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 生子, 骨科, 高H）", replacement: "", sortOrder: 381),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 先婚后爱）", replacement: "", sortOrder: 382),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 相爱相杀, NP, 高H）", replacement: "", sortOrder: 383),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 校园）", replacement: "", sortOrder: 384),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 校园, 1v1）", replacement: "", sortOrder: 385),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 校园, 高H）", replacement: "", sortOrder: 386),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 校园, 生子）", replacement: "", sortOrder: 387),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 因缘邂逅, 1v1）", replacement: "", sortOrder: 388),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 娱乐圈, NTR, 高H）", replacement: "", sortOrder: 389),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 娱乐圈, 强制爱, BDSM, 高H）", replacement: "", sortOrder: 390),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 直播, NP）", replacement: "", sortOrder: 391),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 直播, 师生, 高H）", replacement: "", sortOrder: 392),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 忠犬）", replacement: "", sortOrder: 393),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（双性, 忠犬, 师生）", replacement: "", sortOrder: 394),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（爽文, 黑道）", replacement: "", sortOrder: 395),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（爽文, 末世, NP）", replacement: "", sortOrder: 396),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（爽文, 玄幻, NP）", replacement: "", sortOrder: 397),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（爽文, 直掰弯）", replacement: "", sortOrder: 398),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（爽文, 重口, BDSM, 高H）", replacement: "", sortOrder: 399),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(天作之合)", replacement: "", sortOrder: 400),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（天作之合, 骨科, 高H）", replacement: "", sortOrder: 401),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（田园乡村, 生子, 1v1）", replacement: "", sortOrder: 402),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（万人迷n）", replacement: "", sortOrder: 403),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（网游, 1v1）", replacement: "", sortOrder: 404),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（网游, 破镜重圆）", replacement: "", sortOrder: 405),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(文艺)", replacement: "", sortOrder: 406),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（文艺, 民俗, NP）", replacement: "", sortOrder: 407),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（文艺, 现实主义, BDSM）", replacement: "", sortOrder: 408),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（无CP）", replacement: "", sortOrder: 409),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（无CP, 科幻, 人工智能）", replacement: "", sortOrder: 410),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(无患子)", replacement: "", sortOrder: 411),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(无限流)", replacement: "", sortOrder: 412),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（无限流, 弱强, 受宠攻）", replacement: "", sortOrder: 413),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(武侠)", replacement: "", sortOrder: 414),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（西方, ABO）", replacement: "", sortOrder: 415),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（西方, 强制爱, 骨科, NP）", replacement: "", sortOrder: 416),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（西方, 养成, 强制爱, 骨科, NP）", replacement: "", sortOrder: 417),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（西方, 战争）", replacement: "", sortOrder: 418),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(喜剧)", replacement: "", sortOrder: 419),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（下克上）", replacement: "", sortOrder: 420),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(仙侠)", replacement: "", sortOrder: 421),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(先婚后爱)", replacement: "", sortOrder: 422),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（先婚后爱）", replacement: "", sortOrder: 423),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（先婚后爱, 强制爱, BDSM）", replacement: "", sortOrder: 424),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（先婚后爱, 生子）", replacement: "", sortOrder: 425),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（先虐攻后虐受，换受）", replacement: "", sortOrder: 426),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(现代)", replacement: "", sortOrder: 427),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（现代1v1）", replacement: "", sortOrder: 428),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（现实主义, 暗黑, 强制爱, NP）", replacement: "", sortOrder: 429),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（现实主义, 相爱相杀）", replacement: "", sortOrder: 430),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（相爱相杀）", replacement: "", sortOrder: 431),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（相爱相杀, 1v1）", replacement: "", sortOrder: 432),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（相爱相杀, 美强）", replacement: "", sortOrder: 433),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（相爱相杀, 美强, 受宠攻）", replacement: "", sortOrder: 434),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（相爱相杀, 破镜重圆）", replacement: "", sortOrder: 435),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（相爱相杀, 强制爱）", replacement: "", sortOrder: 436),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（相爱相杀, 强制爱, 触手, 高H）", replacement: "", sortOrder: 437),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(相爱相杀1v1)", replacement: "", sortOrder: 438),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(小甜饼)", replacement: "", sortOrder: 439),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(校园)", replacement: "", sortOrder: 440),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（校园）", replacement: "", sortOrder: 441),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（校园, 1v1）", replacement: "", sortOrder: 442),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（校园, NP）", replacement: "", sortOrder: 443),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（校园, PTSD, NTR, 病娇）", replacement: "", sortOrder: 444),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（校园, 破镜重圆, 1v1）", replacement: "", sortOrder: 445),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（校园, 破镜重圆, 病娇, 1v1）", replacement: "", sortOrder: 446),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（星际, ABO, 弱强）", replacement: "", sortOrder: 447),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（星际, 虫族, 双性, NP, 高H）", replacement: "", sortOrder: 448),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（星际, 互攻）", replacement: "", sortOrder: 449),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（星际, 奇幻, 科幻, 触手, 德语）", replacement: "", sortOrder: 450),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(玄幻)", replacement: "", sortOrder: 451),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（玄幻, 1v1）", replacement: "", sortOrder: 452),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（玄幻, 前世今生, 破镜重圆）", replacement: "", sortOrder: 453),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（玄幻, 强制爱, NP）", replacement: "", sortOrder: 454),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（玄幻, 升级流, 1v1）", replacement: "", sortOrder: 455),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（玄幻, 双性, NP）", replacement: "", sortOrder: 456),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（玄幻, 相爱相杀）", replacement: "", sortOrder: 457),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（玄幻, 重生, 穿越）", replacement: "", sortOrder: 458),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(悬疑)", replacement: "", sortOrder: 459),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（悬疑, NTR, 强制爱, 病娇）", replacement: "", sortOrder: 460),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（悬疑, 暗黑, NP）", replacement: "", sortOrder: 461),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（悬疑, 黑色幽默, 多重视角, 奇幻, 无限流）", replacement: "", sortOrder: 462),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（悬疑, 哨兵向导, 强制爱, NP）", replacement: "", sortOrder: 463),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（悬疑, 无限流, NP）", replacement: "", sortOrder: 464),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（悬疑, 刑侦）", replacement: "", sortOrder: 465),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(养成)", replacement: "", sortOrder: 466),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（养成, 1v1）", replacement: "", sortOrder: 467),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（养成, BDSM）", replacement: "", sortOrder: 468),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（养成, 病娇, NP）", replacement: "", sortOrder: 469),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（养成, 骨科）", replacement: "", sortOrder: 470),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（养成, 破镜重圆, 骨科）", replacement: "", sortOrder: 471),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（养成, 忠犬, 父子）", replacement: "", sortOrder: 472),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(异能)", replacement: "", sortOrder: 473),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（异能, 系统, 骨科, 1v1）", replacement: "", sortOrder: 474),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（因缘邂逅）", replacement: "", sortOrder: 475),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（因缘邂逅, 1v1）", replacement: "", sortOrder: 476),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（因缘邂逅, 公路文）", replacement: "", sortOrder: 477),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(阴差阳错)", replacement: "", sortOrder: 478),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（阴差阳错, NP）", replacement: "", sortOrder: 479),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（阴差阳错, 强制爱）", replacement: "", sortOrder: 480),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（阴差阳错, 下克上）", replacement: "", sortOrder: 481),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（娱乐圈）", replacement: "", sortOrder: 482),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（娱乐圈, 1v1）", replacement: "", sortOrder: 483),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（娱乐圈, 论坛体）", replacement: "", sortOrder: 484),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（原神[原神], 游戏同人, 悲剧, BE, 生子）", replacement: "", sortOrder: 485),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（原始社会, 双性, 强制爱, 民俗）", replacement: "", sortOrder: 486),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（战争, 相爱相杀, 1v1）", replacement: "", sortOrder: 487),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(长篇)", replacement: "", sortOrder: 488),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(正剧)", replacement: "", sortOrder: 489),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（支配服从, 相爱相杀, 破镜重圆, BDSM）", replacement: "", sortOrder: 490),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（支配服从, 因缘邂逅, 忠犬, 下克上, BDSM）", replacement: "", sortOrder: 491),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(直掰弯)", replacement: "", sortOrder: 492),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（直掰弯）", replacement: "", sortOrder: 493),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(直播)", replacement: "", sortOrder: 494),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（直播, 1v1）", replacement: "", sortOrder: 495),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（直播, NP）", replacement: "", sortOrder: 496),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（直播, 无限流, NP, 高H）", replacement: "", sortOrder: 497),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（职业文）", replacement: "", sortOrder: 498),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（职业文, 互攻）", replacement: "", sortOrder: 499),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(治愈)", replacement: "", sortOrder: 500),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(致郁)", replacement: "", sortOrder: 501),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(中篇)", replacement: "", sortOrder: 503),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（忠犬, 女王）", replacement: "", sortOrder: 504),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（重口）", replacement: "", sortOrder: 505),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（开新文中)", replacement: "", sortOrder: 506),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（重口, ABO, 先婚后爱, 高H）", replacement: "", sortOrder: 507),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（重口, NTR, 攻转受）", replacement: "", sortOrder: 508),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（重口, 强制爱, 高H）", replacement: "", sortOrder: 509),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（重口, 双性, 强制爱, NP, 高H）", replacement: "", sortOrder: 510),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（重生, NP）", replacement: "", sortOrder: 511),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（重生, 忠犬）", replacement: "", sortOrder: 512),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(主攻视角)", replacement: "", sortOrder: 513),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（主攻星际）", replacement: "", sortOrder: 514),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(宗教)", replacement: "", sortOrder: 515),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "(总攻)", replacement: "", sortOrder: 516),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（总攻_NP）", replacement: "", sortOrder: 517),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "[BL ]", replacement: "", sortOrder: 518),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "[R18G强强虐身]", replacement: "", sortOrder: 519),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "[叉糕双性调教]", replacement: "", sortOrder: 520),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "[父子伦理cuntboy生子纯爱]", replacement: "", sortOrder: 521),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "【书香门第★九落】", replacement: "", sortOrder: 46),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（剑三[剑侠情缘网络版三], 混合性向, 互攻", replacement: "", sortOrder: 688),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（明星[明星], 破镜重圆, 直掰弯", replacement: "", sortOrder: 724),
        KeywordReplaceRule(scope: SCOPE_SCAN, pattern: "（原神[原神], 游戏同人, 悲剧, BE, 生子", replacement: "", sortOrder: 961),
    ]
}
