import { KeywordReplaceRule } from '../model/KeywordReplaceRule';

/**
 * 关键词替换工具，完整对齐安卓端 util/KeywordReplace.kt 与 PC 端 backend/keyword_replace.py。
 *
 * applyRules：按规则顺序对文本依次执行【字面量】精确字符串替换
 * （pattern 命中即整段替换为 replacement，空串=删除）。
 * 使用 split/join 实现字面量替换（对齐 Kotlin String.replace 的语义），
 * 避免把规则里的正则元字符误当正则、也避免 replacement 中的 $ 被特殊解释。
 */
export class KeywordReplace {
  public static readonly SCOPE_SCAN: string = 'scan'; // 扫描阶段：作用于文件名
  public static readonly SCOPE_PARSE: string = 'parse'; // 解析阶段：作用于 书名/作者/进度/来源

  public static applyRules(text: string | null, rules: KeywordReplaceRule[]): string | null {
    if (text === null || text.length === 0 || rules.length === 0) {
      return text;
    }
    let result: string = text;
    for (const r of rules) {
      const p: string = r.pattern;
      if (p && p.length > 0) {
        result = result.split(p).join(r.replacement);
      }
    }
    return result;
  }

  /**
   * 预置默认关键词替换规则（作用域=扫描阶段，作用于文件名）。
   * 用于去除网文 txt 文件名上常见的平台水印/标记（如 [草2莓]、【lili】 等），
   * 减少用户手动配置工作量。首次启动时由 EntryAbility 按 pattern 幂等补齐；
   * 后续新增预置项也会自动补进已安装实例，无需清数据。
   */
  public static readonly DEFAULT_KEYWORD_RULES: KeywordReplaceRule[] = [
    KeywordReplace.rule('scan', '[草2莓]', '', 1),
    KeywordReplace.rule('scan', '【草2莓', '', 2),
    KeywordReplace.rule('scan', '【草2莓】', '', 3),
    KeywordReplace.rule('scan', '[草 莓]', '', 4),
    KeywordReplace.rule('scan', '【lili】', '', 6),
    KeywordReplace.rule('scan', '（l.i.）', '', 7),
    KeywordReplace.rule('scan', '(l.i.）', '', 8),
    KeywordReplace.rule('scan', '（l.i.)', '', 9),
    KeywordReplace.rule('scan', '(l.i.)', '', 10),
    // —— 以下为 caomei / 3167 937770 水印系列及扩展名修正（与 PC/安卓端同步）——
    // 顺序约定：① 含「の企鹅3167 937770」的完整变体须先于裸「の企鹅3167 937770」；
    // ② 成对括号变体须先于只去开头括号的变体，避免残留孤立前缀/括号。
    KeywordReplace.rule('scan', '..txt', '.txt', 11),
    KeywordReplace.rule('scan', '【草莓】', '', 12),
    KeywordReplace.rule('scan', '【草 莓', '', 13),
    KeywordReplace.rule('scan', '【＋V信kxee6699】', '', 14),
    KeywordReplace.rule('scan', '.3167 937770', '', 15),
    KeywordReplace.rule('scan', '【颜3167 937770', '', 16),
    KeywordReplace.rule('scan', '【Q主caomeiの企鹅3167 937770】', '', 17),
    KeywordReplace.rule('scan', '【Q主caomei】', '', 18),
    KeywordReplace.rule('scan', '_caomeiの企鹅3167 937770_', '', 19),
    KeywordReplace.rule('scan', '【qzcaomeiの企鹅3167 937770', '', 22),
    KeywordReplace.rule('scan', '.QZcaomeiの企鹅3167 937770', '', 23),
    KeywordReplace.rule('scan', '_caomeiの企鹅3167 937770', '', 24),
    KeywordReplace.rule('scan', '.caomeiの企鹅3167 937770', '', 25),
    KeywordReplace.rule('scan', 'の企鹅3167 937770', '', 26),
    KeywordReplace.rule('scan', '[3167 937770]', '', 27),
    KeywordReplace.rule('scan', '3167937770', '', 29),
    KeywordReplace.rule('scan', '_3167 937770', '', 30),
    KeywordReplace.rule('scan', '【3167 937770]', '', 32),
    KeywordReplace.rule('scan', '_.txt', '.txt', 33),
    // —— 与 Android 端同步的默认替换规则 ——
    KeywordReplace.rule('scan', '【YLW】', '', 34),
    KeywordReplace.rule('scan', '『推』', '', 35),
    KeywordReplace.rule('scan', '【昭昭明月BG】', '', 36),
    KeywordReplace.rule('scan', '【昭昭明月BL】', '', 37),
    KeywordReplace.rule('scan', '【推荐】', '', 38),
    KeywordReplace.rule('scan', '【全本校对】', '', 39),
    KeywordReplace.rule('scan', '【全本精校】', '', 40),
    KeywordReplace.rule('scan', '【BL】', '', 41),
    KeywordReplace.rule('scan', '【BG】', '', 42),
    KeywordReplace.rule('scan', '【YLW连载】', '', 43),
    KeywordReplace.rule('scan', '【棠】', '', 44),
    KeywordReplace.rule('scan', '【公众号：推文日记】', '', 45),
    KeywordReplace.rule('scan', '（1-1强制）', '', 47),
    KeywordReplace.rule('scan', '(1v1)', '', 48),
    KeywordReplace.rule('scan', '（1v1）', '', 49),
    KeywordReplace.rule('scan', '（1v1, 高H）', '', 50),
    KeywordReplace.rule('scan', '（1v1, 直掰弯）', '', 51),
    KeywordReplace.rule('scan', '（1v2）', '', 52),
    KeywordReplace.rule('scan', '（1vN）', '', 53),
    KeywordReplace.rule('scan', '（1vn）', '', 54),
    KeywordReplace.rule('scan', '（2025年重修版）', '', 55),
    KeywordReplace.rule('scan', '（3P_强制）', '', 56),
    KeywordReplace.rule('scan', '(ABO)', '', 57),
    KeywordReplace.rule('scan', '（ABO）', '', 58),
    KeywordReplace.rule('scan', '（ABO, 1v1）', '', 59),
    KeywordReplace.rule('scan', '（ABO, NP）', '', 60),
    KeywordReplace.rule('scan', '（ABO, 穿越, 生子）', '', 61),
    KeywordReplace.rule('scan', '（ABO, 高H）', '', 62),
    KeywordReplace.rule('scan', '（ABO, 骨科）', '', 63),
    KeywordReplace.rule('scan', '（ABO, 破镜重圆）', '', 64),
    KeywordReplace.rule('scan', '（ABO, 破镜重圆, 骨科）', '', 65),
    KeywordReplace.rule('scan', '（ABO, 破镜重圆, 生子）', '', 66),
    KeywordReplace.rule('scan', '（ABO, 强制爱, NP, 高H）', '', 67),
    KeywordReplace.rule('scan', '（ABO, 强制爱, 骨科, NP）', '', 68),
    KeywordReplace.rule('scan', '（ABO, 强制爱, 美强）', '', 69),
    KeywordReplace.rule('scan', '（ABO, 强制爱, 异能）', '', 70),
    KeywordReplace.rule('scan', '（ABO, 弱强, 受宠攻）', '', 71),
    KeywordReplace.rule('scan', '（ABO, 生子）', '', 72),
    KeywordReplace.rule('scan', '（ABO, 生子, 高H）', '', 73),
    KeywordReplace.rule('scan', '（ABO, 双性, NP）', '', 74),
    KeywordReplace.rule('scan', '（ABO, 双性, 高H）', '', 75),
    KeywordReplace.rule('scan', '（ABO, 双性, 生子, 产乳）', '', 76),
    KeywordReplace.rule('scan', '（ABO, 天作之合, 1v1）', '', 77),
    KeywordReplace.rule('scan', '（ABO, 西方, 强制爱, NP）', '', 78),
    KeywordReplace.rule('scan', '（ABO, 先婚后爱）', '', 79),
    KeywordReplace.rule('scan', '（ABO, 先婚后爱, 高H）', '', 80),
    KeywordReplace.rule('scan', '（ABO, 先婚后爱, 互攻）', '', 81),
    KeywordReplace.rule('scan', '（ABO, 先婚后爱, 强制爱）', '', 82),
    KeywordReplace.rule('scan', '（ABO, 相爱相杀, 生子, 高H）', '', 83),
    KeywordReplace.rule('scan', '（ABO, 阴差阳错, NTR, NP）', '', 84),
    KeywordReplace.rule('scan', '（ABO, 娱乐圈, 暗恋, 重生）', '', 85),
    KeywordReplace.rule('scan', '（ABO, 娱乐圈, 强制爱）', '', 86),
    KeywordReplace.rule('scan', '（ABO强制爱_all橘）', '', 87),
    KeywordReplace.rule('scan', '(BDSM)', '', 88),
    KeywordReplace.rule('scan', '（BDSM）', '', 89),
    KeywordReplace.rule('scan', '（BE, 美强）', '', 90),
    KeywordReplace.rule('scan', '（BE, 强制爱, NP）', '', 91),
    KeywordReplace.rule('scan', '（BE, 校园）', '', 92),
    KeywordReplace.rule('scan', '(Ending)', '', 93),
    KeywordReplace.rule('scan', '（futa np）', '', 94),
    KeywordReplace.rule('scan', '（H_C, 暗黑, MB）', '', 95),
    KeywordReplace.rule('scan', '（H_C, 暗恋）', '', 96),
    KeywordReplace.rule('scan', '（H_C, 黑色幽默, 美强）', '', 97),
    KeywordReplace.rule('scan', '（H_C, 美强, NP）', '', 98),
    KeywordReplace.rule('scan', '（H_C, 日系, 破镜重圆）', '', 99),
    KeywordReplace.rule('scan', '（H_C, 哨兵向导, 1v1）', '', 100),
    KeywordReplace.rule('scan', '（H_C, 双性, 破镜重圆）', '', 101),
    KeywordReplace.rule('scan', '（H_C, 西方, 强制爱, 高H）', '', 102),
    KeywordReplace.rule('scan', '(Happy)', '', 103),
    KeywordReplace.rule('scan', '（MB）', '', 104),
    KeywordReplace.rule('scan', '（n）', '', 105),
    KeywordReplace.rule('scan', '(NP)', '', 106),
    KeywordReplace.rule('scan', '（NP）', '', 107),
    KeywordReplace.rule('scan', '（NP, BDSM）', '', 108),
    KeywordReplace.rule('scan', '（NP, 高H）', '', 109),
    KeywordReplace.rule('scan', '（NP, 直掰弯）', '', 110),
    KeywordReplace.rule('scan', '(NTR)', '', 111),
    KeywordReplace.rule('scan', '（NTR）', '', 112),
    KeywordReplace.rule('scan', '（NTR, 父子）', '', 113),
    KeywordReplace.rule('scan', '（NTR, 论坛体, 高H）', '', 114),
    KeywordReplace.rule('scan', '（NTR, 强制爱）', '', 115),
    KeywordReplace.rule('scan', '（OE）', '', 116),
    KeywordReplace.rule('scan', '（OE, 骨科, NP, 高H）', '', 117),
    KeywordReplace.rule('scan', '（OE, 惊悚, 美强）', '', 118),
    KeywordReplace.rule('scan', '（OE, 开放关系）', '', 119),
    KeywordReplace.rule('scan', '（OE, 星际, ABO）', '', 120),
    KeywordReplace.rule('scan', '(Open)', '', 121),
    KeywordReplace.rule('scan', '（PTSD, 强制爱）', '', 122),
    KeywordReplace.rule('scan', '(SP _ BDSM)', '', 123),
    KeywordReplace.rule('scan', '（sp）', '', 124),
    KeywordReplace.rule('scan', '（SP训诫）', '', 125),
    KeywordReplace.rule('scan', '(暧昧)', '', 126),
    KeywordReplace.rule('scan', '(暗黑)', '', 127),
    KeywordReplace.rule('scan', '（暗黑, ABO, 骨科）', '', 128),
    KeywordReplace.rule('scan', '（暗黑, 骨科, 下克上, BDSM）', '', 129),
    KeywordReplace.rule('scan', '（暗黑, 强制爱, 1v1, 触手）', '', 130),
    KeywordReplace.rule('scan', '（暗黑, 强制爱, BDSM）', '', 131),
    KeywordReplace.rule('scan', '（暗黑, 强制爱, NP）', '', 132),
    KeywordReplace.rule('scan', '（暗黑, 双性）', '', 133),
    KeywordReplace.rule('scan', '（暗黑, 双性, 前世今生, 无限流）', '', 134),
    KeywordReplace.rule('scan', '（暗黑, 重口, 高H）', '', 135),
    KeywordReplace.rule('scan', '(暗恋)', '', 136),
    KeywordReplace.rule('scan', '（暗恋）', '', 137),
    KeywordReplace.rule('scan', '（暗恋, 1v1）', '', 138),
    KeywordReplace.rule('scan', '（暗恋, NP）', '', 139),
    KeywordReplace.rule('scan', '（暗恋, 天作之合, 互攻）', '', 140),
    KeywordReplace.rule('scan', '（暗恋, 异能）', '', 141),
    KeywordReplace.rule('scan', '（暗恋, 忠犬）', '', 142),
    KeywordReplace.rule('scan', '（暗恋, 重生）', '', 143),
    KeywordReplace.rule('scan', '（悲剧, BE）', '', 144),
    KeywordReplace.rule('scan', '（悲剧, BE, 现实主义）', '', 145),
    KeywordReplace.rule('scan', '（被螃蟹扛著的鱼）', '', 146),
    KeywordReplace.rule('scan', '(产乳)', '', 147),
    KeywordReplace.rule('scan', '(虫族)', '', 148),
    KeywordReplace.rule('scan', '（虫族, 双性, 生子, 产乳, 高H）', '', 149),
    KeywordReplace.rule('scan', '（穿越, NP）', '', 150),
    KeywordReplace.rule('scan', '（穿越, 系统, 美强, 1v1）', '', 151),
    KeywordReplace.rule('scan', '(大纲)', '', 152),
    KeywordReplace.rule('scan', '（大纲, 强制爱, NP）', '', 153),
    KeywordReplace.rule('scan', '(大古代)', '', 154),
    KeywordReplace.rule('scan', '(大未来)', '', 155),
    KeywordReplace.rule('scan', '(大现代)', '', 156),
    KeywordReplace.rule('scan', '(大长篇)', '', 157),
    KeywordReplace.rule('scan', '(大主受视角)', '', 158),
    KeywordReplace.rule('scan', '（第二部）', '', 159),
    KeywordReplace.rule('scan', '（暂时缓更版)', '', 160),
    KeywordReplace.rule('scan', '(第三人称)', '', 161),
    KeywordReplace.rule('scan', '(第一人称)', '', 162),
    KeywordReplace.rule('scan', '(第一人称）', '', 163),
    KeywordReplace.rule('scan', '（东南亚, 天作之合）', '', 164),
    KeywordReplace.rule('scan', '（动物世界, 双性, NP, 人兽, 高H）', '', 165),
    KeywordReplace.rule('scan', '(短篇)', '', 166),
    KeywordReplace.rule('scan', '(多CP高H双男主)', '', 167),
    KeywordReplace.rule('scan', '（多重视角, 1v1）', '', 168),
    KeywordReplace.rule('scan', '（父子）', '', 169),
    KeywordReplace.rule('scan', '（父子, 1v1）', '', 170),
    KeywordReplace.rule('scan', '（父子, 高H）', '', 171),
    KeywordReplace.rule('scan', '(高H)', '', 172),
    KeywordReplace.rule('scan', '（各种炖肉）', '', 173),
    KeywordReplace.rule('scan', '（公路文）', '', 174),
    KeywordReplace.rule('scan', '(攻宠受)', '', 175),
    KeywordReplace.rule('scan', '(宫廷侯爵)', '', 176),
    KeywordReplace.rule('scan', '(狗血)', '', 177),
    KeywordReplace.rule('scan', '(古代)', '', 178),
    KeywordReplace.rule('scan', '(骨科)', '', 179),
    KeywordReplace.rule('scan', '（骨科）', '', 180),
    KeywordReplace.rule('scan', '（骨科）（兄）（np）（骨科,古代,性向）', '', 181),
    KeywordReplace.rule('scan', '（骨科）（兄妹）（np）', '', 182),
    KeywordReplace.rule('scan', '（骨科, BDSM）', '', 183),
    KeywordReplace.rule('scan', '（骨科, NP）', '', 184),
    KeywordReplace.rule('scan', '（骨科, 高H）', '', 185),
    KeywordReplace.rule('scan', '(骨科，男男，年上，甜文)', '', 186),
    KeywordReplace.rule('scan', '（海贼王同人）', '', 187),
    KeywordReplace.rule('scan', '(黑道)', '', 188),
    KeywordReplace.rule('scan', '(黑色幽默)', '', 189),
    KeywordReplace.rule('scan', '（黑色幽默, 暗恋, 阴差阳错, 强制爱）', '', 190),
    KeywordReplace.rule('scan', '（黑色幽默, 反乌托邦, 1v1）', '', 191),
    KeywordReplace.rule('scan', '(互攻)', '', 192),
    KeywordReplace.rule('scan', '（互攻）', '', 193),
    KeywordReplace.rule('scan', '（互攻, 1v1）', '', 194),
    KeywordReplace.rule('scan', '（互攻, 直掰弯）', '', 195),
    KeywordReplace.rule('scan', '（幻想空间, 双性, 快穿, NP）', '', 196),
    KeywordReplace.rule('scan', '(荤素均衡)', '', 197),
    KeywordReplace.rule('scan', '（混合性向）', '', 198),
    KeywordReplace.rule('scan', '（混合性向, NP, BDSM, 高H）', '', 199),
    KeywordReplace.rule('scan', '（混合性向, 暗黑, 西方）', '', 200),
    KeywordReplace.rule('scan', '（混合性向, 惊悚, 悬疑, 雷文）', '', 201),
    KeywordReplace.rule('scan', '（混合性向, 美强, 受宠攻, 高H）', '', 202),
    KeywordReplace.rule('scan', '（混合性向, 虐文）', '', 203),
    KeywordReplace.rule('scan', '（混合性向, 双性, NP, 受宠攻）', '', 204),
    KeywordReplace.rule('scan', '（混合性向, 玄幻, 神怪志异）', '', 205),
    KeywordReplace.rule('scan', '(架空世界)', '', 206),
    KeywordReplace.rule('scan', '（架空世界）', '', 207),
    KeywordReplace.rule('scan', '（架空世界, 强制爱, 1v1）', '', 208),
    KeywordReplace.rule('scan', '（架空世界, 强制爱, NP）', '', 209),
    KeywordReplace.rule('scan', '（架空世界, 双性, 高H）', '', 210),
    KeywordReplace.rule('scan', '（架空世界, 双性, 田园乡村）', '', 211),
    KeywordReplace.rule('scan', '（剑三[剑侠情缘网络版三], 混合性向, 互攻）', '', 212),
    KeywordReplace.rule('scan', '（惊悚, 暗黑, 强制爱, NP）', '', 213),
    KeywordReplace.rule('scan', '（惊悚, 骨科）', '', 214),
    KeywordReplace.rule('scan', '（惊悚, 悬疑, 校园）', '', 215),
    KeywordReplace.rule('scan', '(军政)', '', 216),
    KeywordReplace.rule('scan', '（军政）', '', 217),
    KeywordReplace.rule('scan', '（军政, BDSM）', '', 218),
    KeywordReplace.rule('scan', '（军政, 强制爱, 1v1）', '', 219),
    KeywordReplace.rule('scan', '（军政, 日常, 生子）', '', 220),
    KeywordReplace.rule('scan', '(科幻)', '', 221),
    KeywordReplace.rule('scan', '（科幻, ABO, NP）', '', 222),
    KeywordReplace.rule('scan', '（科幻, ABO, 破镜重圆）', '', 223),
    KeywordReplace.rule('scan', '（科幻, 赛博朋克）', '', 224),
    KeywordReplace.rule('scan', '（科幻, 天作之合, 无限流, 互攻）', '', 225),
    KeywordReplace.rule('scan', '（科幻, 相爱相杀）', '', 226),
    KeywordReplace.rule('scan', '(快穿)', '', 227),
    KeywordReplace.rule('scan', '(雷文)', '', 228),
    KeywordReplace.rule('scan', '(连载)', '', 229),
    KeywordReplace.rule('scan', '（灵魂伴侣, 忠犬）', '', 230),
    KeywordReplace.rule('scan', '(灵异)', '', 231),
    KeywordReplace.rule('scan', '（论坛体）', '', 232),
    KeywordReplace.rule('scan', '(美强)', '', 233),
    KeywordReplace.rule('scan', '（美强）', '', 234),
    KeywordReplace.rule('scan', '（美强, 1v1）', '', 235),
    KeywordReplace.rule('scan', '（美强, 生子, 产乳, 高H）', '', 236),
    KeywordReplace.rule('scan', '（美强, 直掰弯, 受宠攻）', '', 237),
    KeywordReplace.rule('scan', '(民国)', '', 238),
    KeywordReplace.rule('scan', '（民国, NP）', '', 239),
    KeywordReplace.rule('scan', '（民国, NTR, 强制爱, NP, 高H）', '', 240),
    KeywordReplace.rule('scan', '（民国, 民俗, NP, 高H）', '', 241),
    KeywordReplace.rule('scan', '（民国, 虐文）', '', 242),
    KeywordReplace.rule('scan', '（民国, 双性, NP）', '', 243),
    KeywordReplace.rule('scan', '（民国, 双性, 高H）', '', 244),
    KeywordReplace.rule('scan', '（民国, 相爱相杀, 强制爱, NP）', '', 245),
    KeywordReplace.rule('scan', '（民俗, NP, 触手）', '', 246),
    KeywordReplace.rule('scan', '（民俗, 骨科）', '', 247),
    KeywordReplace.rule('scan', '（明星[明星], 破镜重圆, 直掰弯）', '', 248),
    KeywordReplace.rule('scan', '（魔法世界, 强制爱, NP, 触手, 高H）', '', 249),
    KeywordReplace.rule('scan', '（魔幻现实, 美强, 弱强）', '', 250),
    KeywordReplace.rule('scan', '（末世, 架空世界）', '', 251),
    KeywordReplace.rule('scan', '（末世, 科幻）', '', 252),
    KeywordReplace.rule('scan', '（末世, 兽人, 公路文, 美强, NP）', '', 253),
    KeywordReplace.rule('scan', '（末世, 双性, NP）', '', 254),
    KeywordReplace.rule('scan', '（脑洞，梗）', '', 255),
    KeywordReplace.rule('scan', '（脑洞番外梗合集）', '', 256),
    KeywordReplace.rule('scan', '(年上)', '', 257),
    KeywordReplace.rule('scan', '(年下)', '', 258),
    KeywordReplace.rule('scan', '(虐文)', '', 259),
    KeywordReplace.rule('scan', '（虐文, 1v1）', '', 260),
    KeywordReplace.rule('scan', '（虐文, ABO）', '', 261),
    KeywordReplace.rule('scan', '（虐文, ABO, 暗恋, NTR, 生子）', '', 262),
    KeywordReplace.rule('scan', '（虐文, 暗黑, 支配服从）', '', 263),
    KeywordReplace.rule('scan', '（虐文, 病娇, 骨科, 高H）', '', 264),
    KeywordReplace.rule('scan', '（虐文, 骨科）', '', 265),
    KeywordReplace.rule('scan', '（虐文, 受宠攻）', '', 266),
    KeywordReplace.rule('scan', '（虐文, 双性, NP, 高H）', '', 267),
    KeywordReplace.rule('scan', '（虐文, 双性, 强制爱）', '', 268),
    KeywordReplace.rule('scan', '(女王)', '', 269),
    KeywordReplace.rule('scan', '(破镜重圆)', '', 270),
    KeywordReplace.rule('scan', '（破镜重圆）', '', 271),
    KeywordReplace.rule('scan', '（破镜重圆, 1v1）', '', 272),
    KeywordReplace.rule('scan', '（破镜重圆, PTSD, 弱强, 受宠攻）', '', 273),
    KeywordReplace.rule('scan', '（破镜重圆, 高H）', '', 274),
    KeywordReplace.rule('scan', '（破镜重圆, 骨科）', '', 275),
    KeywordReplace.rule('scan', '（破镜重圆, 骨科, 1v1）', '', 276),
    KeywordReplace.rule('scan', '（破镜重圆, 强制爱）', '', 277),
    KeywordReplace.rule('scan', '(其他原创)', '', 278),
    KeywordReplace.rule('scan', '(奇幻)', '', 279),
    KeywordReplace.rule('scan', '（奇幻）', '', 280),
    KeywordReplace.rule('scan', '（奇幻, NP, 互攻, 高H）', '', 281),
    KeywordReplace.rule('scan', '（奇幻, 美强, NP）', '', 282),
    KeywordReplace.rule('scan', '（奇幻, 民俗）', '', 283),
    KeywordReplace.rule('scan', '（奇幻, 魔法世界）', '', 284),
    KeywordReplace.rule('scan', '（奇幻, 爽文, 魔法世界, NP）', '', 285),
    KeywordReplace.rule('scan', '（奇幻, 西方, NTR, 生子, 高H）', '', 286),
    KeywordReplace.rule('scan', '（奇幻, 西方, 互攻, 高H）', '', 287),
    KeywordReplace.rule('scan', '（奇幻, 西方, 美强, 生子, 产乳）', '', 288),
    KeywordReplace.rule('scan', '（奇幻, 血族, 1v1）', '', 289),
    KeywordReplace.rule('scan', '（奇幻, 因缘邂逅）', '', 290),
    KeywordReplace.rule('scan', '（前世今生, 破镜重圆）', '', 291),
    KeywordReplace.rule('scan', '（前世今生, 强制爱, NP）', '', 292),
    KeywordReplace.rule('scan', '(强强)', '', 293),
    KeywordReplace.rule('scan', '(强弱)', '', 294),
    KeywordReplace.rule('scan', '(强制爱)', '', 295),
    KeywordReplace.rule('scan', '（强制爱）', '', 296),
    KeywordReplace.rule('scan', '（强制爱, 1v1）', '', 297),
    KeywordReplace.rule('scan', '（强制爱, NP）', '', 298),
    KeywordReplace.rule('scan', '（强制爱, NP, 高H）', '', 299),
    KeywordReplace.rule('scan', '（强制爱, NP, 直掰弯, BDSM, 高H）', '', 300),
    KeywordReplace.rule('scan', '（强制爱, 克系, 触手, 高H）', '', 301),
    KeywordReplace.rule('scan', '（强制爱, 弱强, NP）', '', 302),
    KeywordReplace.rule('scan', '（强制爱, 上下级）', '', 303),
    KeywordReplace.rule('scan', '(青梅竹马)', '', 304),
    KeywordReplace.rule('scan', '(轻松)', '', 305),
    KeywordReplace.rule('scan', '(清水)', '', 306),
    KeywordReplace.rule('scan', '（求票）', '', 307),
    KeywordReplace.rule('scan', '(人鱼)', '', 308),
    KeywordReplace.rule('scan', '（日常）', '', 309),
    KeywordReplace.rule('scan', '（日常, 1v1）', '', 310),
    KeywordReplace.rule('scan', '（日常, 骨科, 1v1）', '', 311),
    KeywordReplace.rule('scan', '（日常, 生子）', '', 312),
    KeywordReplace.rule('scan', '（日常, 天作之合, 1v1）', '', 313),
    KeywordReplace.rule('scan', '（日常, 相爱相杀, 上下级）', '', 314),
    KeywordReplace.rule('scan', '（肉渣）', '', 315),
    KeywordReplace.rule('scan', '(弱强)', '', 316),
    KeywordReplace.rule('scan', '（弱强）', '', 317),
    KeywordReplace.rule('scan', '（弱强, 1v1）', '', 318),
    KeywordReplace.rule('scan', '（弱强, 骨科, 受宠攻）', '', 319),
    KeywordReplace.rule('scan', '（弱强, 受宠攻）', '', 320),
    KeywordReplace.rule('scan', '（弱强, 直掰弯）', '', 321),
    KeywordReplace.rule('scan', '(三观不正)', '', 322),
    KeywordReplace.rule('scan', '(商战)', '', 323),
    KeywordReplace.rule('scan', '（哨兵向导, NP）', '', 324),
    KeywordReplace.rule('scan', '（神怪志异, ABO, 触手）', '', 325),
    KeywordReplace.rule('scan', '（神怪志异, 破镜重圆）', '', 326),
    KeywordReplace.rule('scan', '（神怪志异, 因缘邂逅, 1v1）', '', 327),
    KeywordReplace.rule('scan', '(生子)', '', 328),
    KeywordReplace.rule('scan', '（生子, 受宠攻）', '', 329),
    KeywordReplace.rule('scan', '(师生)', '', 330),
    KeywordReplace.rule('scan', '（师生, NP, 互攻）', '', 331),
    KeywordReplace.rule('scan', '(受宠攻)', '', 332),
    KeywordReplace.rule('scan', '（受宠攻）', '', 333),
    KeywordReplace.rule('scan', '(受受)', '', 334),
    KeywordReplace.rule('scan', '(双性)', '', 335),
    KeywordReplace.rule('scan', '（双性）', '', 336),
    KeywordReplace.rule('scan', '（双性, 1v1）', '', 337),
    KeywordReplace.rule('scan', '（双性, 1v1, 高H）', '', 338),
    KeywordReplace.rule('scan', '（双性, NP）', '', 339),
    KeywordReplace.rule('scan', '（双性, NP, 高H）', '', 340),
    KeywordReplace.rule('scan', '（双性, NTR）', '', 341),
    KeywordReplace.rule('scan', '（双性, NTR, NP）', '', 342),
    KeywordReplace.rule('scan', '（双性, NTR, NP, 高H）', '', 343),
    KeywordReplace.rule('scan', '（双性, NTR, 高H）', '', 344),
    KeywordReplace.rule('scan', '（双性, 产乳, BDSM, 高H）', '', 345),
    KeywordReplace.rule('scan', '（双性, 单元剧, 高H）', '', 346),
    KeywordReplace.rule('scan', '（双性, 父子）', '', 347),
    KeywordReplace.rule('scan', '（双性, 父子, NP）', '', 348),
    KeywordReplace.rule('scan', '（双性, 父子, 高H）', '', 349),
    KeywordReplace.rule('scan', '（双性, 高H）', '', 350),
    KeywordReplace.rule('scan', '（双性, 骨科）', '', 351),
    KeywordReplace.rule('scan', '（双性, 骨科, NP）', '', 352),
    KeywordReplace.rule('scan', '（双性, 互攻, 受受）', '', 353),
    KeywordReplace.rule('scan', '（双性, 克系, NP, 高H）', '', 354),
    KeywordReplace.rule('scan', '（双性, 快穿, NP, 高H）', '', 355),
    KeywordReplace.rule('scan', '（双性, 快穿, 高H）', '', 356),
    KeywordReplace.rule('scan', '（双性, 论坛体, 高H）', '', 357),
    KeywordReplace.rule('scan', '（双性, 美强, 1v1）', '', 358),
    KeywordReplace.rule('scan', '（双性, 美强, NP）', '', 359),
    KeywordReplace.rule('scan', '（双性, 美强, 弱强, 受转攻）', '', 360),
    KeywordReplace.rule('scan', '（双性, 民俗, 产乳, 高H）', '', 361),
    KeywordReplace.rule('scan', '（双性, 破镜重圆）', '', 362),
    KeywordReplace.rule('scan', '（双性, 破镜重圆, 1v1, 高H）', '', 363),
    KeywordReplace.rule('scan', '（双性, 破镜重圆, 高H）', '', 364),
    KeywordReplace.rule('scan', '（双性, 破镜重圆, 强制爱, NP）', '', 365),
    KeywordReplace.rule('scan', '（双性, 破镜重圆, 生子）', '', 366),
    KeywordReplace.rule('scan', '（双性, 前世今生, 无限流, 生子）', '', 367),
    KeywordReplace.rule('scan', '（双性, 强制爱）', '', 368),
    KeywordReplace.rule('scan', '（双性, 强制爱, 1v1, 高H）', '', 369),
    KeywordReplace.rule('scan', '（双性, 强制爱, NP）', '', 370),
    KeywordReplace.rule('scan', '（双性, 强制爱, NP, 高H）', '', 371),
    KeywordReplace.rule('scan', '（双性, 强制爱, 高H）', '', 372),
    KeywordReplace.rule('scan', '（双性, 强制爱, 骨科, 高H）', '', 373),
    KeywordReplace.rule('scan', '（双性, 强制爱, 美强, 生子）', '', 374),
    KeywordReplace.rule('scan', '（双性, 生子）', '', 375),
    KeywordReplace.rule('scan', '（双性, 生子, 1v1）', '', 376),
    KeywordReplace.rule('scan', '（双性, 生子, 1v1, 互攻）', '', 377),
    KeywordReplace.rule('scan', '（双性, 生子, NP）', '', 378),
    KeywordReplace.rule('scan', '（双性, 生子, NP, 高H）', '', 379),
    KeywordReplace.rule('scan', '（双性, 生子, 高H）', '', 380),
    KeywordReplace.rule('scan', '（双性, 生子, 骨科, 高H）', '', 381),
    KeywordReplace.rule('scan', '（双性, 先婚后爱）', '', 382),
    KeywordReplace.rule('scan', '（双性, 相爱相杀, NP, 高H）', '', 383),
    KeywordReplace.rule('scan', '（双性, 校园）', '', 384),
    KeywordReplace.rule('scan', '（双性, 校园, 1v1）', '', 385),
    KeywordReplace.rule('scan', '（双性, 校园, 高H）', '', 386),
    KeywordReplace.rule('scan', '（双性, 校园, 生子）', '', 387),
    KeywordReplace.rule('scan', '（双性, 因缘邂逅, 1v1）', '', 388),
    KeywordReplace.rule('scan', '（双性, 娱乐圈, NTR, 高H）', '', 389),
    KeywordReplace.rule('scan', '（双性, 娱乐圈, 强制爱, BDSM, 高H）', '', 390),
    KeywordReplace.rule('scan', '（双性, 直播, NP）', '', 391),
    KeywordReplace.rule('scan', '（双性, 直播, 师生, 高H）', '', 392),
    KeywordReplace.rule('scan', '（双性, 忠犬）', '', 393),
    KeywordReplace.rule('scan', '（双性, 忠犬, 师生）', '', 394),
    KeywordReplace.rule('scan', '（爽文, 黑道）', '', 395),
    KeywordReplace.rule('scan', '（爽文, 末世, NP）', '', 396),
    KeywordReplace.rule('scan', '（爽文, 玄幻, NP）', '', 397),
    KeywordReplace.rule('scan', '（爽文, 直掰弯）', '', 398),
    KeywordReplace.rule('scan', '（爽文, 重口, BDSM, 高H）', '', 399),
    KeywordReplace.rule('scan', '(天作之合)', '', 400),
    KeywordReplace.rule('scan', '（天作之合, 骨科, 高H）', '', 401),
    KeywordReplace.rule('scan', '（田园乡村, 生子, 1v1）', '', 402),
    KeywordReplace.rule('scan', '（万人迷n）', '', 403),
    KeywordReplace.rule('scan', '（网游, 1v1）', '', 404),
    KeywordReplace.rule('scan', '（网游, 破镜重圆）', '', 405),
    KeywordReplace.rule('scan', '(文艺)', '', 406),
    KeywordReplace.rule('scan', '（文艺, 民俗, NP）', '', 407),
    KeywordReplace.rule('scan', '（文艺, 现实主义, BDSM）', '', 408),
    KeywordReplace.rule('scan', '（无CP）', '', 409),
    KeywordReplace.rule('scan', '（无CP, 科幻, 人工智能）', '', 410),
    KeywordReplace.rule('scan', '(无患子)', '', 411),
    KeywordReplace.rule('scan', '(无限流)', '', 412),
    KeywordReplace.rule('scan', '（无限流, 弱强, 受宠攻）', '', 413),
    KeywordReplace.rule('scan', '(武侠)', '', 414),
    KeywordReplace.rule('scan', '（西方, ABO）', '', 415),
    KeywordReplace.rule('scan', '（西方, 强制爱, 骨科, NP）', '', 416),
    KeywordReplace.rule('scan', '（西方, 养成, 强制爱, 骨科, NP）', '', 417),
    KeywordReplace.rule('scan', '（西方, 战争）', '', 418),
    KeywordReplace.rule('scan', '(喜剧)', '', 419),
    KeywordReplace.rule('scan', '（下克上）', '', 420),
    KeywordReplace.rule('scan', '(仙侠)', '', 421),
    KeywordReplace.rule('scan', '(先婚后爱)', '', 422),
    KeywordReplace.rule('scan', '（先婚后爱）', '', 423),
    KeywordReplace.rule('scan', '（先婚后爱, 强制爱, BDSM）', '', 424),
    KeywordReplace.rule('scan', '（先婚后爱, 生子）', '', 425),
    KeywordReplace.rule('scan', '（先虐攻后虐受，换受）', '', 426),
    KeywordReplace.rule('scan', '(现代)', '', 427),
    KeywordReplace.rule('scan', '（现代1v1）', '', 428),
    KeywordReplace.rule('scan', '（现实主义, 暗黑, 强制爱, NP）', '', 429),
    KeywordReplace.rule('scan', '（现实主义, 相爱相杀）', '', 430),
    KeywordReplace.rule('scan', '（相爱相杀）', '', 431),
    KeywordReplace.rule('scan', '（相爱相杀, 1v1）', '', 432),
    KeywordReplace.rule('scan', '（相爱相杀, 美强）', '', 433),
    KeywordReplace.rule('scan', '（相爱相杀, 美强, 受宠攻）', '', 434),
    KeywordReplace.rule('scan', '（相爱相杀, 破镜重圆）', '', 435),
    KeywordReplace.rule('scan', '（相爱相杀, 强制爱）', '', 436),
    KeywordReplace.rule('scan', '（相爱相杀, 强制爱, 触手, 高H）', '', 437),
    KeywordReplace.rule('scan', '(相爱相杀1v1)', '', 438),
    KeywordReplace.rule('scan', '(小甜饼)', '', 439),
    KeywordReplace.rule('scan', '(校园)', '', 440),
    KeywordReplace.rule('scan', '（校园）', '', 441),
    KeywordReplace.rule('scan', '（校园, 1v1）', '', 442),
    KeywordReplace.rule('scan', '（校园, NP）', '', 443),
    KeywordReplace.rule('scan', '（校园, PTSD, NTR, 病娇）', '', 444),
    KeywordReplace.rule('scan', '（校园, 破镜重圆, 1v1）', '', 445),
    KeywordReplace.rule('scan', '（校园, 破镜重圆, 病娇, 1v1）', '', 446),
    KeywordReplace.rule('scan', '（星际, ABO, 弱强）', '', 447),
    KeywordReplace.rule('scan', '（星际, 虫族, 双性, NP, 高H）', '', 448),
    KeywordReplace.rule('scan', '（星际, 互攻）', '', 449),
    KeywordReplace.rule('scan', '（星际, 奇幻, 科幻, 触手, 德语）', '', 450),
    KeywordReplace.rule('scan', '(玄幻)', '', 451),
    KeywordReplace.rule('scan', '（玄幻, 1v1）', '', 452),
    KeywordReplace.rule('scan', '（玄幻, 前世今生, 破镜重圆）', '', 453),
    KeywordReplace.rule('scan', '（玄幻, 强制爱, NP）', '', 454),
    KeywordReplace.rule('scan', '（玄幻, 升级流, 1v1）', '', 455),
    KeywordReplace.rule('scan', '（玄幻, 双性, NP）', '', 456),
    KeywordReplace.rule('scan', '（玄幻, 相爱相杀）', '', 457),
    KeywordReplace.rule('scan', '（玄幻, 重生, 穿越）', '', 458),
    KeywordReplace.rule('scan', '(悬疑)', '', 459),
    KeywordReplace.rule('scan', '（悬疑, NTR, 强制爱, 病娇）', '', 460),
    KeywordReplace.rule('scan', '（悬疑, 暗黑, NP）', '', 461),
    KeywordReplace.rule('scan', '（悬疑, 黑色幽默, 多重视角, 奇幻, 无限流）', '', 462),
    KeywordReplace.rule('scan', '（悬疑, 哨兵向导, 强制爱, NP）', '', 463),
    KeywordReplace.rule('scan', '（悬疑, 无限流, NP）', '', 464),
    KeywordReplace.rule('scan', '（悬疑, 刑侦）', '', 465),
    KeywordReplace.rule('scan', '(养成)', '', 466),
    KeywordReplace.rule('scan', '（养成, 1v1）', '', 467),
    KeywordReplace.rule('scan', '（养成, BDSM）', '', 468),
    KeywordReplace.rule('scan', '（养成, 病娇, NP）', '', 469),
    KeywordReplace.rule('scan', '（养成, 骨科）', '', 470),
    KeywordReplace.rule('scan', '（养成, 破镜重圆, 骨科）', '', 471),
    KeywordReplace.rule('scan', '（养成, 忠犬, 父子）', '', 472),
    KeywordReplace.rule('scan', '(异能)', '', 473),
    KeywordReplace.rule('scan', '（异能, 系统, 骨科, 1v1）', '', 474),
    KeywordReplace.rule('scan', '（因缘邂逅）', '', 475),
    KeywordReplace.rule('scan', '（因缘邂逅, 1v1）', '', 476),
    KeywordReplace.rule('scan', '（因缘邂逅, 公路文）', '', 477),
    KeywordReplace.rule('scan', '(阴差阳错)', '', 478),
    KeywordReplace.rule('scan', '（阴差阳错, NP）', '', 479),
    KeywordReplace.rule('scan', '（阴差阳错, 强制爱）', '', 480),
    KeywordReplace.rule('scan', '（阴差阳错, 下克上）', '', 481),
    KeywordReplace.rule('scan', '（娱乐圈）', '', 482),
    KeywordReplace.rule('scan', '（娱乐圈, 1v1）', '', 483),
    KeywordReplace.rule('scan', '（娱乐圈, 论坛体）', '', 484),
    KeywordReplace.rule('scan', '（原神[原神], 游戏同人, 悲剧, BE, 生子）', '', 485),
    KeywordReplace.rule('scan', '（原始社会, 双性, 强制爱, 民俗）', '', 486),
    KeywordReplace.rule('scan', '（战争, 相爱相杀, 1v1）', '', 487),
    KeywordReplace.rule('scan', '(长篇)', '', 488),
    KeywordReplace.rule('scan', '(正剧)', '', 489),
    KeywordReplace.rule('scan', '（支配服从, 相爱相杀, 破镜重圆, BDSM）', '', 490),
    KeywordReplace.rule('scan', '（支配服从, 因缘邂逅, 忠犬, 下克上, BDSM）', '', 491),
    KeywordReplace.rule('scan', '(直掰弯)', '', 492),
    KeywordReplace.rule('scan', '（直掰弯）', '', 493),
    KeywordReplace.rule('scan', '(直播)', '', 494),
    KeywordReplace.rule('scan', '（直播, 1v1）', '', 495),
    KeywordReplace.rule('scan', '（直播, NP）', '', 496),
    KeywordReplace.rule('scan', '（直播, 无限流, NP, 高H）', '', 497),
    KeywordReplace.rule('scan', '（职业文）', '', 498),
    KeywordReplace.rule('scan', '（职业文, 互攻）', '', 499),
    KeywordReplace.rule('scan', '(治愈)', '', 500),
    KeywordReplace.rule('scan', '(致郁)', '', 501),
    KeywordReplace.rule('scan', '(中篇)', '', 503),
    KeywordReplace.rule('scan', '（忠犬, 女王）', '', 504),
    KeywordReplace.rule('scan', '（重口）', '', 505),
    KeywordReplace.rule('scan', '（开新文中)', '', 506),
    KeywordReplace.rule('scan', '（重口, ABO, 先婚后爱, 高H）', '', 507),
    KeywordReplace.rule('scan', '（重口, NTR, 攻转受）', '', 508),
    KeywordReplace.rule('scan', '（重口, 强制爱, 高H）', '', 509),
    KeywordReplace.rule('scan', '（重口, 双性, 强制爱, NP, 高H）', '', 510),
    KeywordReplace.rule('scan', '（重生, NP）', '', 511),
    KeywordReplace.rule('scan', '（重生, 忠犬）', '', 512),
    KeywordReplace.rule('scan', '(主攻视角)', '', 513),
    KeywordReplace.rule('scan', '（主攻星际）', '', 514),
    KeywordReplace.rule('scan', '(宗教)', '', 515),
    KeywordReplace.rule('scan', '(总攻)', '', 516),
    KeywordReplace.rule('scan', '（总攻_NP）', '', 517),
    KeywordReplace.rule('scan', '[BL ]', '', 518),
    KeywordReplace.rule('scan', '[R18G强强虐身]', '', 519),
    KeywordReplace.rule('scan', '[叉糕双性调教]', '', 520),
    KeywordReplace.rule('scan', '[父子伦理cuntboy生子纯爱]', '', 521),
    KeywordReplace.rule('scan', '【书香门第★九落】', '', 46),
    KeywordReplace.rule('scan', '（剑三[剑侠情缘网络版三], 混合性向, 互攻', '', 688),
    KeywordReplace.rule('scan', '（明星[明星], 破镜重圆, 直掰弯', '', 724),
    KeywordReplace.rule('scan', '（原神[原神], 游戏同人, 悲剧, BE, 生子', '', 961),
];

  private static rule(scope: string, pattern: string, replacement: string, sortOrder: number): KeywordReplaceRule {
    const r: KeywordReplaceRule = new KeywordReplaceRule();
    r.scope = scope;
    r.pattern = pattern;
    r.replacement = replacement;
    r.sortOrder = sortOrder;
    r.enabled = true;
    r.isBuiltin = 1;
    r.createdAt = Date.now();
    return r;
  }
}
